### ISSUE TITLE
IE, maxinstances="1" running 2.45 and I'm seeing the following

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#100]
![image](https://cloud.githubusercontent.com/assets/6800679/6653702/5a89680e-ca72-11e4-9ad1-0f1336a9fff3.png)

Many instances of ie web driver with 1 iexplorer.exe.
It looks like things are NOT being cleaned up/ killed after the tests..

teardown on our tests does call 
	getDriver().quit();

Anyone have suggestions as to what could be causing this behavior?

Thanks!

cktech529

**Comment by smccarthy** [comment]
@cktech529 I don't think this would be a SeleniumGridExtras issue. As long as you call the quit method on the driver, it should quit both the browser and the iedriverserver (or chromedriver).

**Comment by cktech529** [comment]
True, sorry, I was desperate. It's a strange issue for sure :). <-- I thought Grid Extras was calling native kill task OS calls...

**Comment by dlai0001** [comment]
I saw that too, but I think it's a seleniumgrid in general.  On the same day the 2.45 update came out, IE also released an update, and they created their own SeleniumDriverServer, http://www.microsoft.com/en-us/download/details.aspx?id=44069

I believe Selenium Grid Extras might need to be updated to use the Microsoft Supported bindings.  But I don't know for sure.  My temporary work around is back out the IE updates for the last 3 months, and working off of 2.44

**Comment by cktech529** [comment]
Thanks, I'll give it a shot :)!

**Comment by smccarthy** [comment]
@cktech529 Are you still seeing this issue with the latest SeleniumGridExtras ? Or even with the version of SeleniumGridExtras that you were using before?

**Comment by cktech529** [comment]
I'll have to look, we gave up on IE testing for now.

**Comment by smccarthy** [comment]
Closing as no response back in > 6 months. If still an issue, please post back or open a new issue. Thanks.
