### ISSUE TITLE
Strange characters/ text on startup of node. 

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#103]
C:\ROOT\Startup_Scripts>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedr
iver_2.45.0_x64bit.exe -Dwebdriver.chrome.driver=\tmp\webdriver\chromedriver\chr
omedriver_2.14_32bit.exe -cp "Z:\Selenium_Jars\Selenium-Grid-Extras-Jar.jar;\tmp
\webdriver\2.45.0.jar" org.openqa.grid.selenium.GridLauncher -role wd  -friendly
HostName SEL-W7NODE-11 -nodeConfig node_5555.json -log log\node_5555.log
SSttaarting ChromeDrritvienrg  2CShtarting rCohmreoDmreiDvr.eir1 42..3113454.317
3 4(53d6v4er 2.14.313455c400edf2e2c5005667c9 a(a3d645c400edf2e2c500566c9aa096063
f707c9cf) o7n (3d645c400edf2 ep2ocr5t0 0496063e70876c894c
Only local con0n566c9aa09e6ct0i6o3ne)s  on aproer t 4a4l79053
Only local cloowed.
ic9cf) on port n18n9e6c1t
ally local connections are oalnlso waerde.
lowed.
Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on
port 23163
Only local connections are allowed.

**Comment by smccarthy** [comment]
@cktech529 Do you still see this with 1.10.0 ? What version where you using? It looked like a possible parallel thread issue.

**Comment by ludiofines** [comment]
Hi @smccarthy I have noted the same thing in win7 64 node. Any ideas?

C:\Users\user\selenium>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedri
ver_2.52.0_Win32bit.exe -Dwebdriver.edge.driver="C:\Program Files (x86)\Microsof
t Web Driver\MicrosoftWebDriver.exe" -Dwebdriver.chrome.driver=\tmp\webdriver\ch
romedriver\chromedriver_2.21_32bit.exe -cp "C:\Users\user\Downloads\SeleniumGrid
Extras-1.11.8-SNAPSHOT-jar-with-dependencies.jar;\tmp\webdriver\2.49.1.jar" org.
openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName webgui-tester-wind
ows -nodeConfig node_5555.json -log log\node_5555.log
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on
port 2019
Only local connections are allowed.
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on
port 6912
Only local connections are allowed.
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on
port 38877
Only local connections are allowed.
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on
port 46589
Only local connections are allowed.

**Comment by ludiofines** [comment]
nvm. I had different issue with the path and browser wasn't starting.

**Comment by smccarthy** [comment]
No response back in > 6 months. Closing issue. Please post back or open a new issue if you still see this issue.
