### ISSUE TITLE
InvalidOperationException appears when setting implicit wait parameter

### ISSUE THREAD

**Issue by domaspuras** [groupon/Selenium-Grid-Extras#113]
The exception appears when trying to set implicitly wait seconds for Remote WebDriver of Selenium Grid Extras, however it works fine with native Selenium Grid.

`driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromMilliseconds(5000));`

Please let me know if it might be caused by some of specific Hub or Node configuration. 

**Exception stack trace:**
*SetUp : System.InvalidOperationException : For input string: "5000.0"
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTimeouts.ImplicitlyWait(TimeSpan timeToWait)*

**Comment by andydavidsmith** [comment]
We are also getting this issue, we are using the dotnet bindings with Selenium 2.44.0

**Comment by rgonalo** [comment]
Last Selenium-Grid-Extras release (1.7.1) has a library conflict with selenium 2.44.0 and higher.
The issue was solved in https://github.com/groupon/Selenium-Grid-Extras/issues/74, but there are no new releases after this commit.

**Comment by lindavz28** [comment]
*bump*  Could we get a new release with the latest fixes?

**Comment by domaspuras** [comment]
It's fixed in 1.9.0 version
