### ISSUE TITLE
Need your inputs to create Selenium grid on cloud infrastructure.

### ISSUE THREAD

**Issue by TeqBuk** [groupon/Selenium-Grid-Extras#116]
Hi Dimacus,

Currently I am using Selenium Grid Extras in my project. The grid is created on physical machines. I have few queries as below:

1) I need your help on how to automate Internet Explorer settings like Delete browsing history on Exit, Clearing History, cookies, and cache etc.
2) For every click action my mouse moves on the Internet explorer browser. How to remove this constraint?

The second part of my queries is around taking Physical machine to cloud virtual machines. I want to use Selenium Grid Extras in my cloud. I want to create virtual machines for every OS-Browser combination. My queries are:

1) Please suggest how have you managed to create so many virtual machines of all possible operating systems on the cloud. I am trying to figure out whether any cloud provides the facility to create Mac, Windows and Linux virtual machines together but none in the market is providing as on date. Can you suggest your inputs?

Thanks,
Mahendra Rathod.

**Comment by smccarthy** [comment]
@TeqBuk Does using the "ie.ensureCleanSession" capability work (for a clean browser session each time) ?

As for the IE click action moving your mouse, I haven't noticed this, so I can't help there.

As for using the cloud, one way is to create an AMI with java and the browsers you want installed. Also include the selenium grid extras configuration already setup. By "already setup", I mean the first time run configs have already been created, so it won't ask you again. Than have a script start the selenium-grid-extras jar file on login, and have an auto-logon script. Now when you boot up X instances of the AMI, it will auto logon and start the selenium-grid-extras jar.

You can get as fancy as you like with your AMI and provisioning. Me personally, I had the AMI only have java, flash, and the browsers installed. Than I used the user-data field (in AWS) to automatically download the jar file, create the config files, and everything else I needed. I don't know of any cloud provider for OSX/Mac.

**Comment by smccarthy** [comment]
@TeqBuk I also started a chef recipe for selenium-grid-extras : https://github.com/smccarthy/chef-selenium-grid-extras . Do these solutions (This post and my comment from 4 days ago) work for you?

**Comment by smccarthy** [comment]
Closing as no response back in > 6 months.
