### ISSUE TITLE
Defining proxy

### ISSUE THREAD

**Issue by Shnitzelil** [groupon/Selenium-Grid-Extras#120]
I'm working behind enterprise proxy and the GRID Extra failed to down load the drivers.

**Comment by chapmanc** [comment]
I just got past this at my work Shnitzelil. You have to define http.proxyHost, http.proxyPort and https.proxyHost and https.proxyPort in the cmd line ex: 

```java -Dhttp.proxyHost=<proxy> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<proxy> -Dhttps.ProxyPort=<port> -jar SeleniumGridExtras.jar```

**Comment by docvego** [comment]
Can confirm this works.  If you're proxy also requires authentication, you'll need to also need to add in

-Dhttp.proxyUser
-Dhttp.proxyPassword

If you have a windows domain AD user authenticating, you may need to use two backslashes \\ instead of the normal one backslash \

**Comment by smccarthy** [comment]
@Shnitzelil Since you opened this, can this be closed with @chapmanc and @docvego suggestions/fix/workaround ?

**Comment by Shnitzelil** [comment]
Sorry,

I missed that email/suggestion... anyway I'm no longer working with
Extra-Grid so sadly I'll not test it.
At least not in the near future.

Sorry and thanks

On Tue, Jul 14, 2015 at 5:37 PM, Shawn McCarthy <notifications@github.com>
wrote:

> @Shnitzelil <https://github.com/Shnitzelil> Since you opened this, can
> this be closed with @chapmanc <https://github.com/chapmanc> and @docvego
> <https://github.com/docvego> suggestions/fix/workaround ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/120#issuecomment-121257165>
> .
>



-- 
Kobi Gana קובי גנה

**Comment by smccarthy** [comment]
No worries! Thanks for letting me know. Closing this issue.

**Comment by gibet** [comment]
Beware ! @chapmanc is right on his command, but read it carefully : There's no P on `-Dhttps.ProxyPort=`, it should be `-Dhttps.proxyPort=` .... or it would not works....
I lost 30 minutes figguring out why it won't works just because I copy/paste it as is
