### ISSUE TITLE
IE 10,11 deleting browsing history on exit settings issue

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#122]
For IE 10 and 11 is there any capability within selenium/selenium grid extras which would ensure "Delete browsing history on exit" setting remains checked throughout. 
As of now after I run a few tests the settings seems to disappear on its own and due to this the application under test fails as IE opens the last browsed URL on start-up.
![capture](https://cloud.githubusercontent.com/assets/8623750/7853116/47d82458-0527-11e5-919e-844bfac10007.PNG)

**Comment by smccarthy** [comment]
I did a quick google search, but couldn't find where this setting was stored. The other IE settings we can set with SeleniumGridExtras can be set (Protected Mode and Mixed Mode) in the registry. If you can find out where this is stored, we can add an endpoint to set it within SeleniumGridExtras.

**Comment by sohammukherjee** [comment]
I'm also searching for a registry level endpoint settings for this feature. Right now I'm able to overcome this problem by doing some settings in Group Policy.

**Comment by smccarthy** [comment]
@sohammukherjee Does using this capability help ? ie.ensureCleanSession

https://code.google.com/p/selenium/wiki/DesiredCapabilities

**Comment by smccarthy** [comment]
Btw, I think it does a clean history on startup.

**Comment by sohammukherjee** [comment]
I solve this problem by tweaking some registry settings of IE.
