### ISSUE TITLE
Error on node reboot on Linux

### ISSUE THREAD

**Issue by eelessam** [groupon/Selenium-Grid-Extras#123]
I'm trying to reboot a node on linux. If I ssh on to the machine and do shutdown now -r it works, and because of the cronjob I've set up the node restarts when the machine comes back up.

However after 10 test runs I don't think my node is being restarted and also when I go to the URL of my node:3000/reboot I get this error message on the screen:

    {
      "exit_code": 1,
      "out": [],
      "error": [
        "Problems in running {\"exit_code\":1,\"out\":[],\"error\":[\"This task was not implemented on Linux com.groupon.seleniumgridextras.tasks.RebootNode\"]}",
        "java.io.IOException: Cannot run program \"{\"exit_code\":1,\"out\":[],\"error\":[\"This\": error\u003d2, No such file or directory"
      ],
      "command": [
        "{\"exit_code\":1,\"out\":[],\"error\":[\"This task was not implemented on Linux com.groupon.seleniumgridextras.tasks.RebootNode\"]}"
      ]
    }

Is it not possible to do the reboot on Linux or have I done something wrong here? I've got this working on my OSX machines.

Any help would be appreciated. 

Thanks

**Comment by kreynolds** [comment]
Seeing the same issue myself with the latest release on Ubuntu 14.04

**Comment by smccarthy** [comment]
@kreynolds  @eelessam  I can try to take a look at this.

**Comment by smccarthy** [comment]
A fix has been merged to master #143 . Once a release is cut, you can verify.

**Comment by smccarthy** [comment]
This fix made it into version 1.10.1 which was released today. Please verify and let us know if its fixed for you.

**Comment by smccarthy** [comment]
@kreynolds @eelessam Any update on this? Please let us know if its fixed and if this can be closed. Thank you. I can close this out if I don't hear anything back after a week.

**Comment by kreynolds** [comment]
@smccarthy I'm running 1.10.1 but I actually just disabled reboot, ensure the clients clean up after themselves, and I haven't had any problems that make we want to re-enable reboot so I guess .. good job :)

**Comment by eelessam** [comment]
Sorry guys I'm using Windows now so haven't got the machine to verify if this is still an issue.

**Comment by smccarthy** [comment]
This seems similar to a new issue : https://github.com/groupon/Selenium-Grid-Extras/issues/182

**Comment by smccarthy** [comment]
Closing this. Re-open if still an issue. I think it was fixed in #143
