### ISSUE TITLE
Windows problems with cookies on chrome

### ISSUE THREAD

**Issue by eelessam** [groupon/Selenium-Grid-Extras#125]
When using selenium grid extras on windows 7 with chrome my test blows up because it cannot access the cookies of the browser. If using the same version of chrome (latest) and the chromedriver (latest), and running the vanilla selenium-standalone-server jar my test works. Is Selenium Grid Extras doing something strange when it starts the jar like passing in a flag or something?

**Comment by smccarthy** [comment]
@eelessam There is nothing special when starting the nodes. It uses the JVM arguments (mine for OSX):
-Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.16_32bit

Are you still having this issue? What version of SeleniumGridExtras (1.10.0 is the latest). What version of Chromedriver? What version of Chrome?

**Comment by smccarthy** [comment]
Closing since no response after > 6 months. Please post back or open a new issue if this is still a problem.

Thank you.
