### ISSUE TITLE
Mobile and Tablet support

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#127]
Is there any way to start a node on Mobile or tablet via Selenium Grid extras??

**Comment by smccarthy** [comment]
I think there was a pull request a few months back for Appium support. It should be in the latest release. I haven't used it myself, but I know when you go through the initial setup flow, it asks if this node will be an Appium node.

**Comment by smccarthy** [comment]
@sohammukherjee Can this be closed, as there is Appium support in the latest couple of releases?

**Comment by sohammukherjee** [comment]
Yes...
Thanks a ton...
