### ISSUE TITLE
Grid Hub auto restart

### ISSUE THREAD

**Issue by VinceBZH** [groupon/Selenium-Grid-Extras#132]
Is it possible to schedule automatic restart of the computer that hosts the Selenium Grid Hub ?
If yes I don't know how...
Thanks

**Comment by smccarthy** [comment]
Are you talking about after X amount of tests, restart the machine? That is an option in the config files (and during initial setup).

Or are you talking about restarting the machine at a specific time (every day at 6am for example)? If this is the case, in Windows it can be done with the Task Scheduler.

**Comment by smccarthy** [comment]
Closing as no response in almost a year. Please feel free to re-open a new issue if you still have questions
