### ISSUE TITLE
Mass Deployment

### ISSUE THREAD

**Issue by bbhenry** [groupon/Selenium-Grid-Extras#133]
Is there a way to massively deploy Selenium-Grid-Extra to multiple windows servers as nodes? For example, by copying the jar file and config files to the windows servers. But it still knows it my first time running the jar. How do you guys deploy to multiple server at Groupon?

**Comment by cktech529** [comment]
We have been doing the following: Jar goes on system (hub), Nodes mount a share to that...
Scheduled task launches grid extras on hub/ node pointing the common shared jar...
(maybe not the best approach but works)

**Comment by smccarthy** [comment]
To have it NOT know its the first time running the jar, just copy or create the config files before running the jar. If the config files exist ( I forget exactly which one ), it won't do the "First Time Startup" setup.

**Comment by bbhenry** [comment]
Thanks guys. I have finalized the automated deployment steps (99% automation) of Selenium Grid Extra on Modern IE Vagrant boxes provided by Microsoft on https://github.com/bbhenry/ie-selenium-extra 

I found out that on Windows boxes, you need to put the preconfigured files in `C:/Windows/System32/`. 
Files include:
```
selenium_grid_extras_config.json.example
selenium_grid_extras_config.json
node_5555.json
```
