### ISSUE TITLE
Appium doesn't get restarted 

### ISSUE THREAD

**Issue by eelessam** [groupon/Selenium-Grid-Extras#136]
Hi on all 3 releases since Appium has been supported, I have been unable to get the restart working properly. If I simply enter java -jar Selenium-Grid-Extras.jar, it will start Appium (and a desktop node) and attach it to the grid.

However if I try to do it as a cronjob or a Launchctl script it only starts the desktop node and doesn't start Appium.

I'm using OSX Yosemite

**Comment by rgonalo** [comment]
Hi, I'm using Selenium-Grid-Extras 1.10.0 in OSX Yosemite with an Appium node and a desktop node. I start it with a launchctl script and both nodes start properly after reboot.

Do you have any error on grid_extras.log?

**Comment by eelessam** [comment]
Hi Rgonalo thank for the reply,

I do get the following error in the log:

    02 Jul 2015 13:40:05 [main] INFO  grid.GridStarter  - {"exit_code":0,"out":["Background process started, check log for output"],"error":[],"command":["/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.16_32bit -cp /Users/testing/Downloads/selenium-extras/SeleniumGridExtras-1.8.0-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.46.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName PICMAC02.local -nodeConfig node_5555.json -log log/node_5555.log"]}
    02 Jul 2015 13:40:05 [main] INFO  grid.GridStarter  - appium -p 4723 --log-timestamp --nodeconfig /Users/testing/Downloads/selenium-extras/appium_node_4723.json --log /Users/testing/Downloads/selenium-extras/log/appium_node_4723.log
    02 Jul 2015 13:40:05 [pool-1-thread-1] INFO  threads.ExecuteOsTaskCallable  - Starting to wait for command to finish in background: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.16_32bit -cp /Users/testing/Downloads/selenium-extras/SeleniumGridExtras-1.8.0-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.46.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName PICMAC02.local -nodeConfig node_5555.json -log log/node_5555.log
    02 Jul 2015 13:40:05 [main] WARN  seleniumgridextras.ExecuteCommand  - Problems in running appium -p 4723 --log-timestamp --nodeconfig /Users/testing/Downloads/selenium-extras/appium_node_4723.json --log  /Users/testing/Downloads/selenium-extras/log/appium_node_4723.log  
    java.io.IOException: Cannot run program "appium": error=2, No such file or directory
    02 Jul 2015 13:40:05 [main] INFO  grid.GridStarter  - {"exit_code":1,"out":[],"error":["Problems in running appium -p 4723 --log-timestamp --nodeconfig /Users/testing/Downloads/selenium-extras/appium_node_4723.json --log /Users/testing/Downloads/selenium-extras/log/appium_node_4723.log","java.io.IOException: Cannot run program \"appium\": error=2, No such file or directory"],"command":["appium -p 4723 --log-timestamp --nodeconfig /Users/testing/Downloads/selenium-extras/appium_node_4723.json --log /Users/testing/Downloads/selenium-extras/log/appium_node_4723.log"]}

The command I use to start appium is just 'appium' which is what is set up in the config for the appium node. Strange as I can start it myself. Any ideas?

**Comment by rgonalo** [comment]
Launchctl PATH does not contain /usr/local/bin, so it cannot find appium.
Use absolute path instead of just 'appium':
(installed with npm)
`"appiumStartCommand": "/usr/local/bin/node /usr/local/bin/appium",`
(installed with Appium.dmg)
`"/Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium",`

**Comment by eelessam** [comment]
That worked thanks very much!
