### ISSUE TITLE
How to choose which IP as the Teardown 

### ISSUE THREAD

**Issue by bbhenry** [groupon/Selenium-Grid-Extras#137]
I am running Win7 in a Virtualbox VM. When I run selenium grid extra as the node in this VM and connecting to a hub in the same network, I see the following error. 
```
SetupTeardownProxy unknown version,Connect to 10.0.2.15:5555 [/10.0.2.15] failed: connect timed out
```
![image](https://cloud.githubusercontent.com/assets/667944/8444044/7a84f1e0-1f41-11e5-9620-c8c4f2728e70.png)

Looks like the Node is registered okay, but somehow the IP address being used on the SetupTeardownProxy is the private one on the VM. VM has 2 network interface. How do I tell Selenium Grid Extra to use the correct IP for the Proxy. I can't seem to find it in the config files.

**Comment by smccarthy** [comment]
I believe you can use the host parameter in your node config file. In the configuration of the node json config file, there is (or you can add) a host option, with the ip you want. Does this work? If not, what is currently in your node_5555.json config file? If host is not there, try adding it like this:
    “host”: ip,

Do either of these work?

**Comment by bbhenry** [comment]
I will give it a try when I get a chance with the host parameter

**Comment by bbhenry** [comment]
It worked, thank you.
