### ISSUE TITLE
Kill_pid error

### ISSUE THREAD

**Issue by dirathea** [groupon/Selenium-Grid-Extras#138]
I want to kill process via kill_pid, but when i enter http://mrdevtest01:3000/kill_pid?id=916, the respond was
```json
{
  "exit_code": 1,
  "out": [
    ""
  ],
  "error": [
    "ERROR: The process \"916916\" not found.\r"
  ],
  "command": [
    "taskkill -F -IM 916916"
  ]
}
```
I think the framework wrong writing the process id,

Thank you

**Comment by smccarthy** [comment]
Hi @dirathea , Which version of Selenium-Grid-Extras, and what OS is your node that you tried this on?

Thank you.

**Comment by dirathea** [comment]
Sorry for missing version,
I use latest Selenium-Grid-Extras (1.10), on windows 7
The step that I tried was :
/ps for check process id
/kill_pid?id=processIdFromPs

**Comment by smccarthy** [comment]
Ok thanks. I noticed this on Mac OSX as well (with 1.10). I will look into it.

**Comment by smccarthy** [comment]
I found the problem. It was duplicating the pid in ExecuteOSTask.execute() . Fixed in https://github.com/groupon/Selenium-Grid-Extras/pull/141 .

**Comment by smccarthy** [comment]
This has been merged into master. Will be ready to verify once a release is cut.

**Comment by smccarthy** [comment]
@dirathea This is in 1.10.1 release from today. Please verify and let us know if its fixed for you.

**Comment by dirathea** [comment]
Hi @smccarthy Thank you for fixing this feature.
I have tried it and it's work properly now :+1: 
Let's close this issue now
