### ISSUE TITLE
Possible to use with SeleniumRC?

### ISSUE THREAD

**Issue by pataquets** [groupon/Selenium-Grid-Extras#139]
I just need the 'restart after X builds' feature. If everything else is passed thru, that woud be a lifesaver for me since I have lots of legacy tests.
TIA.

**Comment by smccarthy** [comment]
It might be possible to update the config files after you do the initial setup, but I don't recommend it ( I have never tested RC with Selenium Grid Extras ).

**Comment by smccarthy** [comment]
@pataquets Can this be closed?

**Comment by dimacus** [comment]
No plan to support obsolete technology. However, you can try by manually adding the Selenium RC's node config for each node... no guarantee it will work though.
