### ISSUE TITLE
Google Chrome version not detected - Due to ExecuteCommand not taking a String array anymore

### ISSUE THREAD

**Issue by smccarthy** [groupon/Selenium-Grid-Extras#145]
execRuntime inside of ExecuteCommand.java should take a String array to run :
Runtime.getRuntime().exec(String[]);

Otherwise commands with spaces don't work out so well.

**Comment by dimacus** [comment]
i think you fixed your own bug buddy https://github.com/groupon/Selenium-Grid-Extras/pull/146/files
