### ISSUE TITLE
Support for Microsoft Edge

### ISSUE THREAD

**Issue by Chris2m** [groupon/Selenium-Grid-Extras#151]
Microsoft Edge WebDriver bindings have been added to the 2.47 selenium release. For more information see: http://stackoverflow.com/a/30055334

Are there any plans to support for edge as a part of the selenium grid extras project?

**Comment by smccarthy** [comment]
Yes I think Selenium-Grid-Extras will support Edge. It would be pretty easy to just add a similar question to whether "This node will support Internet Explorer". I guess we'd have to download the Edge driver though. Also we would have to support the auto update for Edge driver.

**Comment by Chris2m** [comment]
Yes, I assume so. It is important to note that both Edge and Internet Explorer 11 can be installed in parallel on Windows 10. In addition, the [Microsoft WebDriver](https://www.microsoft.com/en-us/download/details.aspx?id=48212) might get updated automatically as a part of Windows Updates. So as a first step it might be enough to just offer the Edge Capabilities. Currently calling `Capability.getCapabilityFor("edge")` will result in a NPE.

**Comment by dimacus** [comment]
Don't have access to windows 10 box.

Any chance we can give you a jar to test on your machine?

Sent via Payphone

**Comment by smccarthy** [comment]
I have a Windows 10 VM that I can try it on.

**Comment by Chris2m** [comment]
I am happy to test if you provide the jar.

Sent from my phone
Am 12.08.2015 1:17 vorm. schrieb "Dima Kovalenko" <notifications@github.com
>:

> Don't have access to windows 10 box.
>
> Any chance we can give you a jar to test on your machine?
>
> Sent via Payphone
>

**Comment by dimacus** [comment]
Alright guys, give this a try

https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.11.0

I'm not familiar enough with Edge to write the auto download and installer
of the Edge server so you will have to do that by hand. Let me know if it
works though.

On Wed, Aug 12, 2015 at 3:04 AM, Chris2m <notifications@github.com> wrote:

> I am happy to test if you provide the jar.
>
> Sent from my phone
> Am 12.08.2015 1:17 vorm. schrieb "Dima Kovalenko" <
> notifications@github.com
> >:
>
> > Don't have access to windows 10 box.
> >
> > Any chance we can give you a jar to test on your machine?
> >
> > Sent via Payphone
> >
> > > On Aug 10, 2015, at 7:37 PM, Chris2m <notifications@github.com> wrote:
> > >
> > > Yes, I assume so. It is important to note that both Edge and Internet
> > Explorer 11 can be installed in parallel on Windows 10. In addition, the
> > Microsoft WebDriver might get updated automatically as a part of Windows
> > Updates. So as a first step it might be enough to just offer the Edge
> > Capabilities. Currently calling Capability.getCapabilityFor("edge") will
> > result in a NPE.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/groupon/Selenium-Grid-Extras/issues/151#issuecomment-130108424
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/151#issuecomment-130193520>
> .
>



-- 
-Dima Kovalenko
-------------------------

Good judgment comes from experience, and experience comes from bad judgment.
--Frederick P. Brooks

**Comment by Chris2m** [comment]
Hi Dimacus,

Thanks for providing the pre-release so quickly.

My initial test failed, because the system property `webdriver.edge.driver` was not set:

    org.openqa.selenium.WebDriverException: The path to the driver executable must be set
    by the webdriver.edge.driver system property;
    for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver. 
    The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687
    Command duration or timeout: 2.25 seconds

I found a workaround by adding `-Dwebdriver.edge.driver="C:\Program Files (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe"` to `node_5555.bat`. Once the line was added Microsoft Edge WebDriver worked fine. Since the file seems to be re-generated upon starting or rebooting the grid this is not a permanent solution.

Is there another way of specifying the web driver path or could you default to that standard location?

Thanks,
Christian

**Comment by dimacus** [comment]
gotcha, so it's a simple work around as adding the -D property to the batch
file, i can live with that. Let me try 1.11.1

On Wed, Aug 12, 2015 at 1:14 PM, Chris2m <notifications@github.com> wrote:

> Hi Dimacus,
>
> Thanks for providing the pre-release so quickly.
>
> My initial test failed, because the system property webdriver.edge.driver
> was not set:
>
> org.openqa.selenium.WebDriverException: The path to the driver executable must be set
> by the webdriver.edge.driver system property;
> for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver.
> The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687
> Command duration or timeout: 2.25 seconds
>
> I found a workaround by adding -Dwebdriver.edge.driver="C:\Program Files
> (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe" to node_5555.bat. Once
> the line was added Microsoft Edge WebDriver worked fine. Since the file
> seems to be re-generated upon starting or rebooting the grid this is not a
> permanent solution.
>
> Is there another way of specifying the web driver path or could you
> default to that standard location?
>
> Thanks,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/151#issuecomment-130377769>
> .
>



-- 
-Dima Kovalenko
-------------------------

Good judgment comes from experience, and experience comes from bad judgment.
--Frederick P. Brooks

**Comment by Chris2m** [comment]
Thanks - that sounds like plan. Let me know when the update is available and I am happy to verify the workaround.

**Comment by dimacus** [comment]
Just pushed 1.11.1 pre-release, it has the -D flag for edge pointing to the location you gave (I'm assuming default installation path?)

https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.11.1

**Comment by Chris2m** [comment]
Yes, that is the default installation path. Will check and report back.

2015-08-12 21:48 GMT+02:00 Dima Kovalenko <notifications@github.com>:

**Comment by Chris2m** [comment]
Bad news - now selenium node is not started. The log shows:

    12 Aug 2015 23:17:40 [main] INFO  tasks.StartGrid  - Attempting to start Grid Nodes
    12 Aug 2015 23:17:40 [main] INFO  config.Config  - {}
    12 Aug 2015 23:17:40 [main] INFO  seleniumgridextras.SeleniumGridExtras  - {"exit_code":1,"out":[],"error":["java.lang.NullPointerException"]}

Let me know if you need more information.

**Comment by Chris2m** [comment]
Just checked the code. The property needs to be quoted or the spaces escaped.

See: https://github.com/groupon/Selenium-Grid-Extras/commit/43f03a3c10179d5e110b7ea501ee91d9e9f67d0a

**Comment by dimacus** [comment]
Alright try 1.11.2, i've put single quotes in the -D property... seriously
wish i had access to a windows 10 box, testing would be instant... sigh

https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.11.2

On Wed, Aug 12, 2015 at 5:31 PM, Chris2m <notifications@github.com> wrote:

> Just checked the code. The property needs to be quoted or the spaces
> escaped.
>
> See: 43f03a3
> <https://github.com/groupon/Selenium-Grid-Extras/commit/43f03a3c10179d5e110b7ea501ee91d9e9f67d0a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/151#issuecomment-130454334>
> .
>



-- 
-Dima Kovalenko
-------------------------

Good judgment comes from experience, and experience comes from bad judgment.
--Frederick P. Brooks

**Comment by Chris2m** [comment]
Will test later today. I am using a virtual box image from modern.ie on my
mac (ie 11 for windows 10 contains edge).

Sent from my phone
Am 13.08.2015 4:18 nachm. schrieb "Dima Kovalenko" <notifications@github.com
>:

> Alright try 1.11.2, i've put single quotes in the -D property... seriously
> wish i had access to a windows 10 box, testing would be instant... sigh
>
> https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.11.2
>

**Comment by smccarthy** [comment]
Hi @Chris2m , just curious, where did you find a Windows 10 VM on modern.ie ? I only see Windows XP, Vista, 7, 8 and 8.1 .

**Comment by Chris2m** [comment]
Not sure if attachments are supported. See screenshot for windows 10
download.

Sent from my phone
Am 13.08.2015 7:30 nachm. schrieb "Shawn McCarthy" <notifications@github.com

**Comment by smccarthy** [comment]
I don't see a screenshot. I am on this page , http://dev.modern.ie/tools/vms/mac/ and in the Virtual Machine dropdown, I can't find Windows 10. Right above the virtual machine dropdown list I see "Most recent VM build 20150601"

**Comment by Chris2m** [comment]
The grid still does not start. I am getting an NPE and the batch `node_5555.bat` is not even created.

    13 Aug 2015 22:12:28 [pool-1-thread-1] INFO  threads.ExecuteOsTaskCallable  - Starting to wait for command to finish in background: java -cp "C:\selenium\SeleniumGridExtras-1.11.2-SNAPSHOT-jar-with-dependencies.jar;\tmp\webdriver\2.47.1.jar" org.openqa.grid.selenium.GridLauncher -role hub  -log log\grid_hub.log -hubConfig hub_4444.json
    13 Aug 2015 22:12:28 [main] INFO  tasks.StartGrid  - Attempting to start Grid Nodes
    13 Aug 2015 22:12:28 [main] INFO  config.Config  - {}
    13 Aug 2015 22:12:28 [main] INFO  seleniumgridextras.SeleniumGridExtras  - {"exit_code":1,"out":[],"error":["java.lang.NullPointerException"]}

**Comment by dimacus** [comment]
Yeah on it, I can replicate the NPE locally

Sent via Payphone

**Comment by dimacus** [comment]
Hey @Chris2m can you try this build, it fixed the NPE, but i wont'  upload it to the release page because the auto updater goes crazy about "pre-releases" and still downloads them. This jar fixes the NPE and disables auto updates

https://www.dropbox.com/s/twiup2he4p0399k/SeleniumGridExtras-1.11.4-SNAPSHOT-jar-with-dependencies.jar?dl=0

**Comment by Chris2m** [comment]
Hi @dimacus,

the selenium node is now starting but now the edge Driver path is missing. See below:

    C:\selenium>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedriver_2.47.0_Win32bit.exe -Dwebdriver.chrome.driver=\tmp\webdriver\chromedriver\chromedriver_2.16_32bit.exe -cp "C:\selenium\SeleniumGridExtras-1.11.4-SNAPSHOT-jar-with-dependencies.jar;\tmp\webdriver\2.47.1.jar" org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName DESKTOP-U1Q78FF -nodeConfig node_5555.json -log log\node_5555.log

Therefore, I am back to the error I got at the beginning:

    org.openqa.selenium.WebDriverException: The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver. The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687
    Command duration or timeout: 708 milliseconds
    Build info: version: '2.47.1'

Best,
Christian

**Comment by dimacus** [comment]
Yup I think it's because I tried to be clever and check if edge driver exists in given path before adding it, let me try not to be clever :-P

Sent via Payphone

**Comment by dimacus** [comment]
Ok try the 1.1.5 it forces the -D Edge

https://www.dropbox.com/sh/w38ew549cedyudk/AAAdbcaL_i3m2QUPW_MTXos9a?dl=0

On Sun, Aug 16, 2015 at 10:48 AM, Dima Kovalenko <dima.kovalenko@gmail.com>
wrote:

> Yup I think it's because I tried to be clever and check if edge driver
> exists in given path before adding it, let me try not to be clever :-P
>
> Sent via Payphone
>
> On Aug 16, 2015, at 6:34 AM, Chris2m <notifications@github.com> wrote:
>
> Hi @dimacus <https://github.com/dimacus>,
>
> the selenium node is now starting but now the edge Driver path is missing.
> See below:
>
> C:\selenium>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedriver_2.47.0_Win32bit.exe -Dwebdriver.chrome.driver=\tmp\webdriver\chromedriver\chromedriver_2.16_32bit.exe -cp "C:\selenium\SeleniumGridExtras-1.11.4-SNAPSHOT-jar-with-dependencies.jar;\tmp\webdriver\2.47.1.jar" org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName DESKTOP-U1Q78FF -nodeConfig node_5555.json -log log\node_5555.log
>
> Therefore, I am back to the error I got at the beginning:
>
> org.openqa.selenium.WebDriverException: The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver. The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687
> Command duration or timeout: 708 milliseconds
> Build info: version: '2.47.1'
>
> Best,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/151#issuecomment-131522285>
> .
>
>


-- 
-Dima Kovalenko
-------------------------

Good judgment comes from experience, and experience comes from bad judgment.
--Frederick P. Brooks

**Comment by Chris2m** [comment]
Hi @dimacus,

We are getting closer. Please use double quotes as shown in my comment above and it will work.

With single quotes I am currently getting:

    C:\selenium>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedriver_2.47.0_Win32bit.exe -Dwebdriver.edge.driver='C:\Program Files (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe' -Dwebdriver.chrome.driver=\tmp\webdriver\chromedriver\chromedriver_2.16_32bit.exe -cp "C:\selenium\SeleniumGridExtras-1.11.5-SNAPSHOT-jar-with-dependencies.jar;\tmp\webdriver\2.47.1.jar" org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName DESKTOP-U1Q78FF -nodeConfig node_5555.json -log log\node_5555.log
    Error: Could not find or load main class Files

Best,
Christian

**Comment by dimacus** [comment]
Alright try double quotes
https://www.dropbox.com/sh/w38ew549cedyudk/AAAdbcaL_i3m2QUPW_MTXos9a?dl=0

On Mon, Aug 17, 2015 at 4:23 PM, Chris2m <notifications@github.com> wrote:

> Hi @dimacus <https://github.com/dimacus>,
>
> We are getting closer. Please use double quotes as shown in my comment
> above and it will work.
>
> With single quotes I am currently getting:
>
> C:\selenium>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedriver_2.47.0_Win32bit.exe -Dwebdriver.edge.driver='C:\Program Files (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe' -Dwebdriver.chrome.driver=\tmp\webdriver\chromedriver\chromedriver_2.16_32bit.exe -cp "C:\selenium\SeleniumGridExtras-1.11.5-SNAPSHOT-jar-with-dependencies.jar;\tmp\webdriver\2.47.1.jar" org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName DESKTOP-U1Q78FF -nodeConfig node_5555.json -log log\node_5555.log
> Error: Could not find or load main class Files
>
> Best,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/151#issuecomment-131949105>
> .
>



-- 
-Dima Kovalenko
-------------------------

Good judgment comes from experience, and experience comes from bad judgment.
--Frederick P. Brooks

**Comment by dimacus** [comment]
@Chris2m any chance you had time to test this? If you did I would like to push it as an official release.

Thanks!

**Comment by Chris2m** [comment]
@dimacus Just tested - works like charm!

Thanks for providing this great piece of software. It really relieves some pain of running a selenium grid.

**Comment by dimacus** [comment]
awesome that it works!!! :+1:

**Comment by JuanRodriguezAbarca** [comment]
Hi guys, I am facing some problems trying to run EdgeDriver from the command line. The Driver runs well when is ran from the IDE (IntelliJ or Eclipse) and when is ran from the IntelliJ Terminal. But it doesn't navigate when I am running from the Windows command line. It just open the browser but doesn't get the web page.
