### ISSUE TITLE
Nullpointer exception on start Node in Win7

### ISSUE THREAD

**Issue by Patzifist** [groupon/Selenium-Grid-Extras#154]
public static String getEdgeDriverExecutionPathParam() {
        if (RuntimeConfig.getOS().isWindows()) {;
            return String.format(" -Dwebdriver.edge.driver=\"%s\"", RuntimeConfig.getConfig().getEdgeDriver().getExecutablePath());
        } else {
            return "";
        }
    }

**Comment by ham1** [comment]
Are you able to provide more details on the NPE? Perhaps a stacktrace? As it's not clear, to me at least, what you mean by the code above, does it NPE on the first return statement or the if condition or is this your proposed fix?
Thanks.

**Comment by smccarthy** [comment]
@Patzifist Is this still an issue?

**Comment by smccarthy** [comment]
I was unable to reproduce this with 1.12.2 . Please reopen a new issue if this is still broke.

Thanks.
