### ISSUE TITLE
Tests failing in build

### ISSUE THREAD

**Issue by alexkogon** [groupon/Selenium-Grid-Extras#158]
Hi Dima,

Just checked out your project and tried to build it and I get test failures, is there something wrong on my side? Do you have this in CI?

Results :

Failed tests:   testGetCachedReleaseList(com.groupon.seleniumgridextras.downloader.GridExtrasDownloaderTest): expected:<...,"download_count":29[0],"created_at":"2014-...> but was:<...,"download_count":29[6],"created_at":"2014-...>
  testChromeDriverDString(com.groupon.seleniumgridextras.grid.GridStarterTest)
  testExecute(com.groupon.seleniumgridextras.tasks.DownloadChromeDriverTest): expected:<0.0> but was:<1.0>
  testUnknownHost(com.groupon.seleniumgridextras.utilities.HttpUtilityTest): Expected exception: java.net.UnknownHostException

Tests run: 220, Failures: 4, Errors: 0, Skipped: 0

**Comment by dimacus** [comment]
No CI is broken at the moment and the HTTP tests actually download stuff so
make sure you have internet connection.

Also, when video recording tests are running, i noticed the CLI sometimes
runs out of memory, but never had that issue in the IDE

On Mon, Aug 31, 2015 at 4:34 AM, Alex Kogon <notifications@github.com>
wrote:

> Hi Dima,
>
> Just checked out your project and tried to build it and I get test
> failures, is there something wrong on my side? Do you have this in CI?
>
> Results :
>
> Failed tests:
> testGetCachedReleaseList(com.groupon.seleniumgridextras.downloader.GridExtrasDownloaderTest):
> expected:<...,"download_count":29[0],"created_at":"2014-...> but
> was:<...,"download_count":29[6],"created_at":"2014-...>
>
> testChromeDriverDString(com.groupon.seleniumgridextras.grid.GridStarterTest)
> testExecute(com.groupon.seleniumgridextras.tasks.DownloadChromeDriverTest):
> expected:<0.0> but was:<1.0>
> testUnknownHost(com.groupon.seleniumgridextras.utilities.HttpUtilityTest):
> Expected exception: java.net.UnknownHostException
>
> Tests run: 220, Failures: 4, Errors: 0, Skipped: 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groupon/Selenium-Grid-Extras/issues/158>.
>



-- 
-Dima Kovalenko
-------------------------

Good judgment comes from experience, and experience comes from bad judgment.
--Frederick P. Brooks

**Comment by alexkogon** [comment]
Other download tests seem to work, I have internet; just ran it again and slightly different result:

Failed tests:   testChromeDriverDString(com.groupon.seleniumgridextras.grid.GridStarterTest)
  testExecute(com.groupon.seleniumgridextras.tasks.DownloadChromeDriverTest): expected:<0.0> but was:<1.0>

Tests in error:
  testBadVersion(com.groupon.seleniumgridextras.downloader.GridExtrasDownloaderTest)

Will take a look in an actual debugger when I have a bit more time. Also will try to setup a way to debug getting it working with no net connection but those environments are all on headless vms with firewall connectivity issues and DPI so will have to figure out how to connect a debugger there...

**Comment by alexkogon** [comment]
btw you can get a free "FOSS" open source cloud jenkins setup from CloudBees for your project i think

**Comment by smccarthy** [comment]
Just ran a mvn clean install and no test failures. Closing this issue. Please write a comment if you think it should be reopened.
