### ISSUE TITLE
It is not possible to change the Heap size or other "-X" params of the Hub JVM

### ISSUE THREAD

**Issue by charlescapps** [groupon/Selenium-Grid-Extras#159]
In Config.java, you can see the param string is computed by always prepending "-D" to a key-value pair: 
Consequently, using the "grid_jvm_options" option, it's impossible to set "-Xmx4g" or something like that to increase the heap size of the hub.

I will fix this by adding an additional config option, "grid_jvm_x_options" which is just a raw string you can add to the commandline options.

Here's the faulty code that limits us too much: 
<pre>
protected String mapToJvmParams(Map<String, Object> params) {
        String returnString = "";

        for (String key : params.keySet()) {
            Object value = params.get(key);
            String formattedValue = "";

            if (value instanceof Number) {
                formattedValue = "" + ((Number) value).intValue() + "";
            } else {
                formattedValue = value.toString();
            }

            returnString = returnString + "-D" + key + "=" + formattedValue + " ";
        }

        return returnString;
    }
</pre>

**Comment by charlescapps** [comment]
Thanks for merging my pull request!

**Comment by smccarthy** [comment]
You're welcome!
