### ISSUE TITLE
Need the option to enable/disable Session History Logging

### ISSUE THREAD

**Issue by charlescapps** [groupon/Selenium-Grid-Extras#167]
Any major feature of SGE that can impact performance must be configurable. 

I recently did a heap dump, and discovered that the biggest objects in memory for our Selenium standalone process on our Hub are due to the com.groupon.seleniumgridextras.loggers.SessionHistoryLog data.

Here's a screenshot of the heapdump
![screen shot 2015-10-07 at 10 26 38 am](https://cloud.githubusercontent.com/assets/561671/10345357/f71b804a-6cdd-11e5-945e-138c1967dfc7.png)

So, I will add a feature so that the call in SetupTeardownProxy to create a new SessionHistoryCallable is configurable.

**Comment by smccarthy** [comment]
I hope to look at your PR by this weekend : https://github.com/groupon/Selenium-Grid-Extras/pull/168
Thank you.

**Comment by charlescapps** [comment]
Thanks! Yes, this is a simple idea to allow turning off the session logging. I found that our hub's memory usage went down about 1 GB after using this. 

In the long run, we could figure out why session logging is using so much memory. It's probably just that a lot of logs can be generated when you have a lot of tests! 

I think the best solution is to *not* keep the logs in memory. We could just use log4j or another out-of-the-box solution for logging sessions, not sure what the benefit is of keeping the data in memory.

**Comment by lucacri** [comment]
+1 for this!

**Comment by smccarthy** [comment]
@charlescapps I think you wrote a PR for this, that was merged in. Can this be closed?

**Comment by charlescapps** [comment]
Yes, my bad, I had forgotten to close this. Thanks so much for merging the PR!
