### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by ham1** [groupon/Selenium-Grid-Extras#170]
What is the target Java version for build and running?

It would probably be a good idea to specify it in the pom to make it obvious which version people should target when writing code (I haven't found it obvious from looking around on github - apart from the Java 1.6 branch?). There seem to be a few places which would benefit from Java 7 and 8 language features.

Thanks

**Comment by smccarthy** [comment]
I don't know if it has to do with what you are asking, but I did find this in the pom.xml :
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.6</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by ham1** [comment]
Ah, yes thanks, I missed that. I was looking inside the ```SeleniumGridExtras/pom.xml``` file.

Are there plans to up that to Java 8 to utilise streams and lambdas etc., and because Java 8 is currently the only non-EoL version?

**Comment by smccarthy** [comment]
I have no problem with upping the target , but I am not sure we should go to 1.8 just yet. There are a lot of people using Selenium-Grid-Extras, so it could affect them. Maybe 1.7 is better to jump to for now, and than later jump to 1.8?

@dimacus What are your thoughts?

**Comment by dimacus** [comment]
We had several people asking for target of 1.6... technically Selenium Grid supports 1.6 so trying to be compatible to the version selenium is supporting
