### ISSUE TITLE
Can we increase the video recording time to more than 120 seconds?

### ISSUE THREAD

**Issue by tulasiramgulla** [groupon/Selenium-Grid-Extras#172]
Hi,
We found the videos recorded with a maximum limit of 120 seconds. Is there any possibility to increase this time. We tried with "idle_video_timeout": "300", parameter by placing it in node.json file but the issue is the node.json file is resetting to its default configuration(which we gave at the time of node creation) while we restart the node .Is there any way to customize the json files (node.json, selenium_grid_extras_config.json)?

**Comment by smccarthy** [comment]
@dimacus should:
https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/utilities/threads/video/VideoRecordingThreadPool.java#L40
be:
return startVideoRecording(sessionName, RuntimeConfig.getConfig().getVideoRecording().getIdleTimeout());
?
