### ISSUE TITLE
Improving code readability (starting with consistent formatting)

### ISSUE THREAD

**Issue by ham1** [groupon/Selenium-Grid-Extras#174]
I propose we format all the Java code to some agreed standard.

This will be a start in making the code more readable, and hopefully improve the likelihood of  contributions, or at least make it slightly easier to read/debug etc. For example, some java files use 2 spaces for indents, some use 4, some use tabs, some use a mix. `ConfigPuller.java` has a line of 305 chars, many have lines over 120, and about 200 Java files have lines over 80 chars (which is my preference for a 'soft' limit).

My initial suggestion would be a fairly default IntelliJ formatting option - however I've never found a good solution to formatting Java code across multiple IDEs - has anyone else?

However even if we just started with something for the time being, this would put the code in a better shape for maintenance (including tweaking specific bits of formatting in the future).

The only problems I see are those affecting people who have currently forked the project and diverged, it might be harder for them to pull in changes; or anyone working on something bit at the moment.

Thoughts?

**Comment by smccarthy** [comment]
@ham1 I agree. We should come up with a standard (4 spaces for indents, no super long lines, etc). We don't get a lot of PRs currently, so I don't think we have to worry much about that. Did you want to try to take a stab at this? I have 1 semi-big PR for Marionette, but that should be merged in to master this upcoming week.
