### ISSUE TITLE
Running Multiple Instance of Hubs on a Single Machine

### ISSUE THREAD

**Issue by baclark77** [groupon/Selenium-Grid-Extras#176]
Scenario is that I'm currently trying to run multiple grid hubs on a single machine but with different ports. So my web hub might be 4444, my mobile tablet hub might be 4445, and my mobile phone hub might be 4446.

Is there currently a way with grid extras to run multiple instances of itself as a hub with different ports?

Appreciate any insight!

**Comment by rgonalo** [comment]
Hi @baclark77, 
I have several hubs configured, but it's required a Selenium-Grid-Extras change.
I have requested a pull request to solve it: https://github.com/groupon/Selenium-Grid-Extras/pull/177.

**Comment by baclark77** [comment]
Awesome @rgonalo ! Looking forward to it being brought in!

**Comment by smccarthy** [comment]
@baclark77 Can this be closed? #177 was merged in, in December. You might have to build from source. If not, it should be in the next release.

**Comment by smccarthy** [comment]
Closing as no response back and PR merged in.
