### ISSUE TITLE
REST /reboot command on Linux issues command "shutdown -r now" rather than the "sudo shutdown -r now" that RebootNode.java uses

### ISSUE THREAD

**Issue by gramgit** [groupon/Selenium-Grid-Extras#180]
I have Ubuntu 14.04 LTS

I have completed the sudoers edit and on my grid I can issue "````sudo shutdown -r now````" and not be prompted for a password.  

However if I use the REST API command in my browser I get an error stating that the command needs to be executed as root and the command shown is without the sudo bit :+1: 
````
{
  "exit_code": 1,
  "out": [
    ""
  ],
  "error": [
    "shutdown: Need to be root"
  ],
  "command": [
    "shutdown -r now"
  ]
}
````

**Comment by smccarthy** [comment]
@gramgit Just curious, which version of Selenium Grid Extras are you using? I thought I added sudo in the command for reboot recently.

**Comment by gramgit** [comment]
@smccarthy hi shawn, I'm on the latest release.  1-10-1

**Comment by gramgit** [comment]
@smccarthy re-tested under version 1-11-8 and it now works.  The command being executed is: 
```
{
  "exit_code": 0,
  "out": [
    ""
  ],
  "error": [],
  "command": [
    "sudo shutdown -r now"
  ]
}
```

**Comment by smccarthy** [comment]
Thanks for checking. Closing.
