### ISSUE TITLE
run Selenium-Grid-Extras node as a service in Red Hat 6.6 stuck at the command line

### ISSUE THREAD

**Issue by zackyaz** [groupon/Selenium-Grid-Extras#182]
Hi
i try to create a Selenium-Grid-Extras cookbook like Selenium cookbook .
it install Firefox, chrome and Selenium-Grid-Extras as a service in /etc/init.d/Selenium_Grid_Extras.
so i can run /etc/init.d/Selenium_Grid_Extras start / stop / restart / status
when the config files are hub or hub and node.
       work ok
when it is node only the command "/etc/init.d/Selenium_Grid_Extras start" 
the node is work i can see it in the hub webpage and in the logs
but the command is stuck i am not get a prompt as expected from a service

Best Regards,
Zacky Azoulay
[node_5555.json.txt](https://github.com/groupon/Selenium-Grid-Extras/files/44842/node_5555.json.txt)
[selenium_grid_extras_config.json.txt](https://github.com/groupon/Selenium-Grid-Extras/files/44841/selenium_grid_extras_config.json.txt)
[selenium_hub_extras.txt](https://github.com/groupon/Selenium-Grid-Extras/files/44843/selenium_hub_extras.txt)

**Comment by smccarthy** [comment]
I started a chef cookbook for selenium grid extras as well : https://github.com/smccarthy/chef-selenium-grid-extras . I haven't gotten it working on linux yet though. This is just an FYI.

As for why yours doesn't work, maybe it is because selenium grid extras jar continues to run after you start it? It doesn't return you to the command prompt, since it is still running. What is the last few lines of the prompt that it looks like it is stuck on?

**Comment by zackyaz** [comment]
Hi,

Thank, this is weird because when I run hub or hub and node it work good and I got a prompt
When I  run only hub it stuck

Best Regards,
Zacky Azoulay

**Comment by zackyaz** [comment]
Hi

sorry, finally I found the error.

 In the service I check the hub port when I create only node ( so it was stack on checking) 

	  listen=0
	  while [ $listen -eq 0 ];
	  do
	    listen=`netstat -ltn | awk '{print $4}' | grep "${port}$" | wc -l`
	    sleep 1
	  done

I change the service to check the node port when create only a node and it work fine

The attach is the new service file that work fine on node /hub combination
 
Best Regards,
Zacky Azoulay

[selenium_extras.txt](https://github.com/groupon/Selenium-Grid-Extras/files/73968/selenium_extras.txt)
