### ISSUE TITLE
Run multiple Appium server in a single machine

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#190]
Current architecture allows me run one instance of Appium server on a single machine at port 4723. But there should be a provision to run multiple instances of Appium server on a single machine on different ports as Appium supports multiple instances.

**Comment by rgonalo** [comment]
Hi @sohammukherjee, 
It's possible to run multiple Appium servers on a single machine with Grid Extras. You should create a json file for each Appium server with different ports and add file names to node config files list.

appium_node_4723.json:

    "configuration": {
      ...
      "port": 4723,
      "host": "host_ip",
      "url": "http://host_ip:4723/wd/hub",
      "appiumStartCommand": "appium",
    }

appium_node_4725.json:

    "configuration": {
      ...
      "port": 4725,
      "host": "host_ip",
      "url": "http://host_ip:4725/wd/hub",
      "appiumStartCommand": "appium",
    }

selenium_grid_extras_config.json:

    "node_config_files": [
      "appium_node_4723.json",
      "appium_node_4725.json"
    ],

**Comment by sohammukherjee** [comment]
Thanks a lot @rgonalo

**Comment by chirag-farfetch** [comment]
why we have to create seprate json files for appium and then combine them into one later?

**Comment by chirag-farfetch** [comment]
@rgonalo rgonalo
