### ISSUE TITLE
Prevent Video Recording if using phantomJS

### ISSUE THREAD

**Issue by plessbd** [groupon/Selenium-Grid-Extras#194]
Since phantomJS is headless there is no need to record video.  Generally phantomjs will be running on a headless machine, however for testing I run phantomjs on mac, so it records the screen even though there is no need for it to record.

I am looking into this, but Still wrapping my head around JAVA...

**Comment by smccarthy** [comment]
I agree. This seems like it would be an easy addition. It won't make it in for 1.12.3 , but maybe 1.12.4.

**Comment by smccarthy** [comment]
@plessbd This is a non-issue, since you can just set "record_test_videos" to false in the selenium grid extras config file. If you think otherwise, please comment back and we can reopen and think of a solution.
