### ISSUE TITLE
Available nodes via api call

### ISSUE THREAD

**Issue by chapmanc** [groupon/Selenium-Grid-Extras#200]
Is there any existing api calls to determine if there are available nodes to use for selenium testing. Ideally this would return available browsers for each of the nodes. This would stop the case in which we start the tests but no nodes are available. We could call the api and make sure nodes are available before running the tests.

**Comment by smccarthy** [comment]
@chapmanc Is this the same as https://github.com/groupon/Selenium-Grid-Extras/issues/206

**Comment by chapmanc** [comment]
Not really. I don't care about the web view. I want to call the API during the test, check for an available node and queue for it.

**Comment by smccarthy** [comment]
Well with #206 there would probably be an API behind it that our webview called. So you would call the same API to get the number of available browsers.

**Comment by chapmanc** [comment]
Agreed then. Closing it off.
