### ISSUE TITLE
Why is there a `maxSession` parameter in the hub configuration?

### ISSUE THREAD

**Issue by JustinTulloss** [groupon/Selenium-Grid-Extras#207]
I don't believe that hubs use `maxSession`, do they? Why does it get put into the default config? 

https://github.com/groupon/Selenium-Grid-Extras/blob/e4975cedc265100f36ffb492e4db3a6a1a3413bb/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/config/GridHub.java#L161

**Comment by smccarthy** [comment]
I think the hub does have a maxSession parameter. If you just start the jar:
java -jar selenium-server-standalone-2.53.0.jar -role hub

You see this as the config:
http://localhost:4444/grid/console?config=true&configDebug=true

Config for the hub :
host : null
port : 4444
cleanUpCycle : 5000
timeout : 300000
browserTimeout : 0
newSessionWaitTimeout : -1
grid1Mapping : {}
throwOnCapabilityNotPresent : true
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
prioritizer : null
servlets :

all params :

browserTimeout : 0
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
cleanUpCycle : 5000
host : null
jettyMaxThreads : -1
**maxSession : 5**
newSessionWaitTimeout : -1
nodePolling : 5000
port : 4444
prioritizer : null
role : hub
servlets : []
throwOnCapabilityNotPresent : true
timeout : 300000

**Comment by smccarthy** [comment]
@JustinTulloss If this answer is sufficient, please close this issue. Thank you.

**Comment by JustinTulloss** [comment]
I still don't believe that the option actually does anything, but it sounds like it's a selenium hub problem not a grid extras problem. Also I don't really care :)
