### ISSUE TITLE
Is it possible Sikuli could work via wire protocol?

### ISSUE THREAD

**Issue by djangofan** [groupon/Selenium-Grid-Extras#223]
Is it possible Sikuli could work via wire protocol?

Just a thought.  http://www.sikulix.com/

OR, is there already something similar that exists somewhere?

**Comment by shankarkc** [comment]
Yes it works. I have made it work on grid.
You add sikuli jar to class path on hub using your json file.
"hub_additional_classpath": [
      "./extension-proxy-0.6.jar"
    ]
On the nodes there is no option to add jar in class path. I have opened a defect for the same. As of now workaround is
Nodes can be launched with by adding all-node-extensions-0.6.jar to class path. We are using -cp parameter
"C:\Program Files\Java\jdk1.7.0_79\bin\java.exe" -Dhttp.proxyHost=proxy.ariba.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.ariba.com -Dhttps.proxyPort=8080 -cp "C:\selenium_ex/SeleniumGridExtras-jar-with-dependencies.jar;C:\selenium_ex/all-node-extensions-0.6.jar"  -jar "C:\selenium_ex/SeleniumGridExtras-jar-with-dependencies.jar"

**Comment by smccarthy** [comment]
@djangofan @shankarkc Can this be closed? I can start work on adding additional items to the node classpath soon (maybe)

**Comment by shankarkc** [comment]
Sure. This can be closed. Sikuli works on grid extra. I have it running in
our company Datacenter.

**Comment by smccarthy** [comment]
Ok thanks. Closing this. Djangofan, please use shankarkc's method to run sikuli with selenium-grid-extras.
