### ISSUE TITLE
Is it possible to run Selenium-Grid-Extras as a windows service ?

### ISSUE THREAD

**Issue by sh3m** [groupon/Selenium-Grid-Extras#225]
I have a selenium grid setup by installing the hub and nodes as windows services using NSSM so remote tests can be run without being logged into the remote machine. When I try to do the same with the grid extras the services fail to start. 

Is it possible to do this with the grid extras or does the additional functionality mean it has to be run as an interactive process and not a background service ?

**Comment by smccarthy** [comment]
I don't ever suggest running selenium nodes as a non-interactive process.

With that said, what errors do you get when you try to start the grid extras hub and node as a service?

**Comment by rhehl** [comment]
I had a similar problem, non-interactive and Session 0 is really a bad idea, the Browser behavior is not normal.

My solution for a Headlesstesting Via Jenkins in my case was creating a lokal user inside a Windows VM, and adding a link to the selenium grid extras start bat inside autorun, setting up reboot after each test run, and Opening a RDP session insiede jenkins shell execute via freerdp started over xfb run. and then waiting for the sgextras port to come up.

**Comment by smccarthy** [comment]
Closing this issue. Running as a windows service is not recommended.
