### ISSUE TITLE
Need ability to add new jar to class path on nodes 

### ISSUE THREAD

**Issue by shankarkc** [groupon/Selenium-Grid-Extras#228]
Hi,
selenium grid extra provides ability to add a jar file to path as below on hub.
	"hub_additional_classpath": [
      "./extension-proxy-0.6.jar"
    ]

Similar ability is not provided at node. Can you pls add something like below to add a jar file on nodes aswell?
"node_additional_classpath": [
      "./all-node-extensions-0.6.jar"
    ]

Thanks
Shankar

**Comment by smccarthy** [comment]
Good idea @shankarkc .

**Comment by smccarthy** [comment]
https://github.com/groupon/Selenium-Grid-Extras/pull/234 . This will get merged in before next release (maybe next week).

**Comment by shankarkc** [comment]
Thanks Shawn. It will be useful to run sikuli extension client on grid. A
nice to have feature as part of our automation framework.

**Comment by shankarkc** [comment]
hi Shawn referring to your change line number 193 in below file
SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/GridStarter.java
You should add this to class path only if this is node right ?
As of now it get added even for hubs. We will have this jar only on nodes
and we need to add it to class path ONLY IF THIS IS a NODE.

**Comment by shankarkc** [comment]
My bad. I just reffered the code snippet . Your code is right...You have
modified getWebNodeStartCommand method. Sorry for the confusion.

**Comment by smccarthy** [comment]
@shankarkc Can you verify this works for you now, using Selenium-Grid-Extras 1.12.3 ?

**Comment by shankarkc** [comment]
This works great..You can close this....I am able to run sikuli now with this change
