### ISSUE TITLE
Documentation to use "Marionette"

### ISSUE THREAD

**Issue by eyal919** [groupon/Selenium-Grid-Extras#230]
Hi,
Is Selenium grid extras support "Marionette" web driver?
see: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette

if yes, could you document it?
if no, is there a plan for it?

Thank you for great product

Eyal

**Comment by smccarthy** [comment]
It is definitely in the plan to support Marionette. Pull Requests welcome. It shouldn't be too difficult to add, I think.

**Comment by smccarthy** [comment]
https://github.com/groupon/Selenium-Grid-Extras/pull/231

I started to work on adding Marionette into Selenium Grid Extras. I still have to do a few things:
1) Fix the tests related to driver downloads
2) Get the latest version of Marionette/GeckoDriver. Right now it is hard coded to 0.8.0 (latest as of now)

**Comment by smccarthy** [comment]
I fixed number 2 above. The only thing left is fixing/adding the tests, as well as maybe getting it to work with older versions of marionette. I might skip the support for older versions (below 0.8.0), but we may want to switch the name in our code to geckodriver. I think that is the official name now.

**Comment by smccarthy** [comment]
@eyal919 This has been put into version 1.12.3 , however I think it requires Selenium 3.0 beta (or a new release of selenium server under 2.53.2 ).

**Comment by smccarthy** [comment]
@eyal919 I created a PR #257 which lets you use Selenium 3.0-beta4. I will put this in the next release, 1.12.4 (hopefully later today)

**Comment by smccarthy** [comment]
Closing this. Here is the release . https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.4 . Please comment back or open a new issue if you see anything wrong.

Thank you.
