### ISSUE TITLE
Need a Selenium-Grid-Extras drop with latest code...

### ISSUE THREAD

**Issue by shankarkc** [groupon/Selenium-Grid-Extras#243]
Hi recently there was a code fix that helps to add a jar to node path and hub path. but this release binaries are not available yet. Can you please create release with latest code?
Thanks
Shankar KC

**Comment by smccarthy** [comment]
Hi. I was trying to test out the latest release for a bit first. I was hoping marionette driver would work , but it looks like there is an issue with it. Since there were a lot of other fixes improvements recently, I'll try and make a release this week.

**Comment by shankarkc** [comment]
I see version 1.12.2-snaphshot. It doesn't contain adding additional class
path to node. Can I expect it by end of this week?
Thank you
Shankar KC

**Comment by smccarthy** [comment]
I can try and get a release out today.

**Comment by smccarthy** [comment]
@shankarkc I put out a release today. Please try it out and let us know of any issues.

**Comment by smccarthy** [comment]
Closing this. Duplicate of https://github.com/groupon/Selenium-Grid-Extras/issues/228
