### ISSUE TITLE
SeleniumGridExtrasServlet in hub config but not source

### ISSUE THREAD

**Issue by dave-miles** [groupon/Selenium-Grid-Extras#246]
Hub config has [com.groupon.seleniumgridextras.grid.servlets.SeleniumGridExtrasServlet](https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/config/GridHub.java#L151) but there's no [servlets](https://github.com/groupon/Selenium-Grid-Extras/tree/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/servlets) source for it.

Spotted via the following in the hub log:
```bash
10:32:41.312 WARN [1] org.openqa.grid.web.utils.ExtraServletUtil - The specified class : com.groupon.seleniumgridextras.grid.servlets.SeleniumGridExtrasServlet cannot be instantiated com.groupon.seleniumgridextras.grid.servlets.SeleniumGridExtrasServlet
```

Here's the hub config:
```json
{
  "port": 4444,
  "newSessionWaitTimeout": 25000,
  "servlets": [
    "com.groupon.seleniumgridextras.grid.servlets.SeleniumGridExtrasServlet",
    "com.groupon.seleniumgridextras.grid.servlets.ProxyStatusJsonServlet"
  ],
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "browserTimeout": 120000,
  "timeout": 120000,
  "maxSession": 29
}
```

**Comment by smccarthy** [comment]
Good catch. I see it deleted here : https://github.com/groupon/Selenium-Grid-Extras/commit/b0b09ab9840df7c44abbc34401f061e45c124f2f

I will remove it from the hub config

**Comment by smccarthy** [comment]
It is removed in master and will make it in the next release. Closing this for now.
