### ISSUE TITLE
Question about video recording

### ISSUE THREAD

**Issue by mmilbrath** [groupon/Selenium-Grid-Extras#250]
I've disabled recording by setting "videos_to_keep" to 0 but am seeing the following messages in logs on hub.  Do I not have something configured correctly?   We've been diagnosing some test issues and I'm not absolutely confident I can ignore these messages.

Thanks
--Mike

25 Aug 2016 01:40:18 [Thread-32] INFO  proxies.SetupTeardownProxy  - Waiting for stop command to finish for session: 2a58fc34-33bf-485d-abed-e78f5004185d, output:
{
  "exit_code": 1,
  "out": [],
  "error": [
    "Video Recording is disabled on this node"
  ]
}

**Comment by smccarthy** [comment]
@mmilbrath This might be a bug. I am unsure why you get that INFO message. It might not be harming anything though.

However, can you please try this config option to see if it helps ?
https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/test/resources/fixtures/configs/additional_classpath.json#L35

Basically, add "record_test_videos": false
to the same area as videos_to_keep

**Comment by smccarthy** [comment]
See https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/tasks/VideoRecorder.java#L59

getRecordTestVideos() returns the value of "record_test_videos" from the config file.

I think this is OK. One enhancement might be to check record_test_videos OR if videos_to_keep == 0 . PRs welcome.
