### ISSUE TITLE
Docker image for Selenium-Grid_Extras

### ISSUE THREAD

**Issue by sri85** [groupon/Selenium-Grid-Extras#252]
Hi ,
        I have been long fan of selenium grid extras currently we a selenium grid have 20 nodes running using SG Extras, and i am planning to migrate this grid to docker based , was just wondering if there is an official image for the same?
Has anyone has tried running the SG EXTRA using docker ? Any help/pointer would be useful

**Comment by smccarthy** [comment]
This has been discussed before, at least privately. We think it is a good idea. There is currently not a docker image we provide, but any help would be appreciated.

@dimacus You talked to me about this awhile ago.

**Comment by banuchka** [comment]
there is an example https://github.com/banuchka/selenium_scope/tree/master/SeleniumExtraGrid

**Comment by shankarkc** [comment]
I am working on this.  I am able to  run tests and even capture videos.  But l found grid extra assumes some utility like killall present. It also issues reboot... Which are not working . On Grid nodes browsers crashes occasionally. Extra is not cleaing it. I  didn't see logs for cleaup browser.  I have asked Shawn's help. Once I get it stable i will submit a pull request to this repository.

**Comment by shankarkc** [comment]
By the way i forgot to mention that I have used swarm cluster instead of single machine. It allows me to scale more selenium nodes.

**Comment by elgalu** [comment]
@shankarkc if crashes are happening only on Chrome it might be due to [this](https://github.com/elgalu/docker-selenium/issues/20) and [here a solution](https://github.com/elgalu/docker-selenium/issues/20#issuecomment-250496774)

**Comment by gabecase** [comment]
Any updates on this enhancement? Is there any testing or development work that we the community can pair or assist with? I'd love for their to be an official community provided docker image but want to avoid redundant efforts if possible

**Comment by shankarkc** [comment]
I have created docker images and they work on swarm cluster... Working good
for us.  I am planning to open source it soon. I will update you once its
in public git up.. Eta is about a week. It has even sikuli integration for
ui tests.

**Comment by shankarkc** [comment]
These are the changes that you can expect from docker selenium grid extra:-
This docker image uses docker native swarm cluster and service architecture to spin the containers. In few secs you can scaleup and scaledown the nodes.
It uses SeleniumGridExtra binaries to create grid.
It has Sikuli integration so that user can use it for FileUpload and UI tests.
As its using SeleniumGridExtra you have the ability to download test video and OS level screenshot.
Using this grid you can automte scenarios like file download....File get downloaded on remote node machine....Using sikuli APIs you can transfer it to your local machine.

**Comment by citadis** [comment]
@shankarkc I would be interested if you (or anyone else) has a working dockerfile available.

I have tried to create my own, connecting to an existing hub and nodes in separate docker containers but with no success so far.

**Comment by shankarkc** [comment]
Yes... I have selenium grid extra on docker swarm working end to end.  Our
teams are using it with great success.

**Comment by citadis** [comment]
Thanks @shankarkc . Can you share the relevant docker-compose.yaml and Dockerfiles?

**Comment by mariolameiras** [comment]
I uploaded docker images for selenium-grid-extras for hub, chrome and firefox to the Docker Hub.

You can find the source code here and help me test them: https://github.com/viltgroup/docker-selenium-grid-extras

**Comment by smccarthy** [comment]
Thanks @mariolameiras ! I will close this issue and add a link to your repo in the README.
