### ISSUE TITLE
Geckodriver not being downloaded on version 1.12.3

### ISSUE THREAD

**Issue by alewang** [groupon/Selenium-Grid-Extras#254]
I tried setting up Grid Extras 1.12.3 for geckodriver, but I found the geckodriver binary was not being downloaded. Here is a snippet from my logs about geckodriver:

```
28 Sep 2016 10:44:56 [main] INFO  downloader.GeckoDriverDownloader  - Downloading from https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz
28 Sep 2016 10:44:56 [main] INFO  downloader.Downloader  - Starting to download from https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz
28 Sep 2016 10:44:56 [main] ERROR downloader.Downloader  - java.io.FileNotFoundException: https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz
28 Sep 2016 10:44:56 [main] ERROR downloader.Downloader  - Download failed
```

I notice that the download URL for geckodriver version 0.10.0 is https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz instead. For comparison,

    https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-macos.tar.gz
    https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-mac.tar.gz

**Comment by alewang** [comment]
I've also noticed that geckodriver 0.10.0 is intended for Selenium 3, but the Selenium 2.53.1 jar is being download instead. If I force Grid Extras to try running a Selenium 3 jar (through symlinks under Grid Extras' /tmp directory), the child Selenium process immediately exits since I believe the Main class for Selenium 3 has changed.

I've also noticed that even if I use geckodriver 0.9.0 (again, by using symlinks under /tmp/webdriver/geckodriver), Selenium 2.53.1 is unable to launch geckodriver when running as a node. Selenium 2.53.1 also fails with the same error when running geckodriver 0.10.0

**Comment by smccarthy** [comment]
Thanks @alewang . I will update the geckodriver download url. It appears the geckodriver OSX filename has changed the past 3 versions. I will have it work for 0.10.0 (latest)

**Comment by smccarthy** [comment]
I made the fix to master. I'll try and push out a release tomorrow for the osx fix.

**Comment by alewang** [comment]
Thanks @smccarthy!

The main class used in Selenium 2.53.1 is `org.openqa.grid.selenium.GridLauncher`.

The main class used in Selenium 3.0 is `org.openqa.grid.selenium.GridLauncherV3`. Since Grid Extras explicitly states what the main class should be when building Selenium's command line, launching Selenium will fail when using Selenium 3 jars.

**Comment by smccarthy** [comment]
@alewang Yea I agree. I've been pretty busy in my day job and life, so haven't had much time to make this change. PRs welcome, but I will also try to get this done ASAP

**Comment by alewang** [comment]
Yeah, same here. I'll try taking a look around when I have some time too.

**Comment by smccarthy** [comment]
@alewang I have a fix coming soon I hope...

**Comment by smccarthy** [comment]
Another issue with using selenium 3, is that the node config file changed.

**Comment by smccarthy** [comment]
@alewang Here is my current PR : https://github.com/groupon/Selenium-Grid-Extras/pull/257

A few items are missing, that I mention in the PR . I will try and figure out the rest later.

**Comment by smccarthy** [comment]
@alewang The PR is complete and ready for a review. https://github.com/groupon/Selenium-Grid-Extras/pull/257 . I asked @dimacus to review it as well. I wanted a 2nd pair of eyes, since I haven't been active as a java developer in a few months.

Please feel free to review it as well.

I will try and merge it in as soon as possible.

Thanks!

**Comment by alewang** [comment]
I made a build and did a quick test of the branch. My particular use case seems to be working fine.

I would have liked to add a few features and changes to the config file myself, but I think that's probably too much to go out in a maintenance release. I'm good with the changes!

**Comment by smccarthy** [comment]
merged in. I will work on a release later today

**Comment by smccarthy** [comment]
@alewang https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.4

Closing this ticket. Feel free to comment back if you see issues (or open a new issue).
