### ISSUE TITLE
Generated start_grid_extras.bat does not support spaces in path

### ISSUE THREAD

**Issue by intelligen** [groupon/Selenium-Grid-Extras#263]
If the path to the grid extras jarfile contains spaces when you run it for the first time, the start_grid_extras.bat that is generated will fail because it does not add spaces around the jarfile path.

Steps to reproduce:

1. Create a folder on your desktop called "Selenium Grid Extras"
2. Put the grid extras jarfile into that folder
3. Open a command prompt and cd to that folder
4. Run java -jar <jarfile>
5. Run through the configuration steps to configure the instance as a hub, then after the process starts up, terminate it
6. Run start_grid_extras.bat

Expected behavior: 
The hub should start up.

Actual behavior:
The batch file terminated with an error because there were no quotation marks around the jarfile path.

**Comment by smccarthy** [comment]
I started looking at this one. I think the fix is here :
https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/tasks/UpgradeGridExtrasTask.java#L89

using 
```
        String startCommand = String.format("%s %s -jar '%s'",
                shellFileHeader,
                javaPath,
jarFile);
```
instead of 
```
        String startCommand = String.format("%s %s -jar %s",
                shellFileHeader,
                javaPath,
jarFile);
```

**Comment by smccarthy** [comment]
@intelligen I made the change in master. I don't have a windows computer to test against. Can you try building from master and trying? I added the single quotes around the jar file name, as I showed above.

Thank you.

**Comment by smccarthy** [comment]
Closing as this is fixed. If still an issue, please comment back. Thank you.
