### ISSUE TITLE
Question about driver version updates

### ISSUE THREAD

**Issue by gmarsh123** [groupon/Selenium-Grid-Extras#269]
In the readme there is a node setup point which reads: "You will be asked if you wish to auto update Selenium... If you choose to not auto update, you will be asked what versions of each driver to lock into."

What is meant by "lock" here?
1. Does it just mean that the versions you choose will be downloaded and no more will be in the future?
2. Does it mean that every test you run will use the "locked" driver version?

I'm not currently but intend to start using SGE. I ask as my current node configuration for some nodes I use different driver versions (for older and newer browsers). And I don't want these settings overriden.

Thanks for a great project.

**Comment by smccarthy** [comment]
@gmarsh123 By lock, it means it won't auto download the new driver (keep in mind, Selenium Grid Extras does NOT upgrade the browser itself).

For example, if you choose 1 (YES) to auto update the driver versions, it would download chromedriver 2.25 . Now lets say in a week, 2.26 comes out, the next time selenium grid extras starts, it will download and use chromedriver 2.26.

If you chose 0 (NO), it would not check for new versions of the driver. It will also ask you what version you want to use. So if you don't want the driver version to update, just choose NO (0).

**Comment by gmarsh123** [comment]
@smccarthy thanks for the speedy clarification.

Just to confirm - If I choose 0 (NO) then enter a chrome driver of "2.123" in SGE, but my node.config still states webdriver.chrome.driver="path/to/version/3.456", when that node executes a chrome test it will run with driver version 3.456. Correct?

**Comment by smccarthy** [comment]
@gmarsh123 If you enter 0, and choose chromedriver 2.25 it will save 2.25 to selenium_grid_extras_config.json. It will download chromedriver 2.25 and use that. 

If you manually update selenium_grid_extras_config.json and put 2.24 in that file, it will download 2.24. However, it will not check for newer versions (2.26 for example). When 2.26 comes out, and you want to you use it, you would manually update that file `selenium_grid_extras_config.json` with 2.26, and it will download and start to use that version.

I hope this makes sense.

**Comment by gmarsh123** [comment]
@smccarthy thanks for the answer.

What I am asking in a very round about kind of way is - can I still switch between driver binaries? If I have this scenario:

- selenium_grid_extras_config.json file has "iedriver": {"version": "2.43.0"},
- selenium_grid_extras_config.json file also has "node_config_files": ["node_5555.json"]
- node_5555.json has webdriver.ie.driver = "/mypath/drivers/2.66.0/IEDriverServer.exe"

Will the IE driver version used be 2.66.0?

Thanks,

Gordon

**Comment by smccarthy** [comment]
@gmarsh123 I think my confusion is, there is no `webdriver.ie.driver` in the node_5555.json file. You can still switch driver versions even if you are setup to NOT auto update the driver versions. You just have to modify selenium_grid_extras_config.json with whatever version you want to use.

**Comment by gmarsh123** [comment]
@smccarthy thanks, and apologies for the lack of precision in my questions. I have been somewhat confused myself by posts such as these:

- https://seleniumhq.github.io/docs/grid.html#configuration_of_node_with_json
- http://stackoverflow.com/questions/24290638/selenium-internet-explorer-driver-binary-in-json-configuration
- https://www.linkedin.com/pulse/how-to-make-remote-webdriver-work-for-ie8-somnath-singh

Although the one below does state unmistakably that the config I am suggesting is impossible:

- https://groups.google.com/forum/#!topic/webdriver/mQsCIhPy3Jc
