### ISSUE TITLE
question about configuring the grid extra to kill browser instances on test completion...

### ISSUE THREAD

**Issue by shankarkc** [groupon/Selenium-Grid-Extras#270]
Hi I want to kill the browser instances once my test completes. Grid xtra has tasks to do it as i see in example JSON. But I am not sure how to configure it so that it runs each time when a session ends and kill the opened browsers. I did try adding this section in 
    selenium_grid_exra.json

```
    "tear_down": [
      "com.groupon.seleniumgridextras.tasks.KillAllFirefox",
      "com.groupon.seleniumgridextras.tasks.KillAllChrome"
    ],
```

But i didnt see any logs that informs killing opened browsers. Am i missing sth here?
Here is my Json File

```
{
  "theConfigMap": {
    "auto_start_hub": "0",
    "auto_start_node": "1",
    "default_role": "node",
    "disabled_modules": [
      "com.groupon.seleniumgridextras.tasks.SessionHistory",
      "com.groupon.seleniumgridextras.tasks.RebootNode"
    ],
    "tear_down": [
      "com.groupon.seleniumgridextras.tasks.KillAllFirefox",
      "com.groupon.seleniumgridextras.tasks.KillAllChrome"
    ],
    "node_config_files": [
      "node_5555.json"
    ],
    "hub_config_files": [],
    "hub_config": {},
    "video_recording_options": {
      "videos_to_keep": "40"
    },
    "iedriver": {
      "version": "2.53.1"
    },
    "auto_update_drivers": "1",
    "chromedriver": {
      "version": "2.24"
    },
    "webdriver": {
      "version": "2.53.1"
    }
  }
}
```

Your help is appreciated.
Thanks
ShankarKC

**Comment by smccarthy** [comment]
@shankarkc I am sorry, but I never used those "tear_down" items. I would have to look into the code to see when those get looked at/called. I won't have time for at least a few days. Maybe you can look sooner ?

**Comment by mstankovic86** [comment]
@shankarkc i'm using similar configuration and it's works for me:

"tear_down": [
    "com.groupon.seleniumgridextras.tasks.KillAllChrome"
   ]
I'm not sure about logs that informs killing chrome but it kills every instance of chrome after test completes.

**Comment by smccarthy** [comment]
@shankarkc Can you try this again ? Also, what version are you on? I released 1.12.9 yesterday (though it shouldn't affect this issue at all).

**Comment by shankarkc** [comment]
Thanks. I noticed that it works though i didn't see logs.  Browsers getting closed with  teardown.

**Comment by smccarthy** [comment]
Awesome thanks.

**Comment by smccarthy** [comment]
I'll open an improvement to show it in the logs

**Comment by ambikashri** [comment]
Is there a time limit with which it calls the teardown? For e.g., if I am waiting for an element to appear in the page for more than 2 min the browser instance gets killed. Can I increase this timeout somewhere?

**Comment by sebkap** [comment]
@ambikashri 
You can change this value in hub_4444.json.

Parameters you are looking for are:
  "browserTimeout": 300,
  "timeout": 420,
