### ISSUE TITLE
Selenium 3 node will not start when Grid Extras running as node only

### ISSUE THREAD

**Issue by nvonop** [groupon/Selenium-Grid-Extras#271]
I have noticed that when Grid Extras is started from scratch to generate a clean config for a node, answering the following questions other than default will result in a configuration that will not create a bat file to start the node.

Run Firefox = 1
Run InternetExplorer = 1
Run Chrome = 1
Restart = 0
Auto Login = 0
Would you like WebDriver etc to auto update? = 0
Webdriver Version = 3.0.1
IEDriver = 3.0.0
Gecko Driver = 0.11.1
Chrome Driver = 2.24
Chrome Driver = 32 Bit
IE Driver = 32 Bit
Store Configs in Central Location = 0

[node_5555.txt](https://github.com/groupon/Selenium-Grid-Extras/files/547696/node_5555.txt)
[selenium_grid_extras_config.txt](https://github.com/groupon/Selenium-Grid-Extras/files/547697/selenium_grid_extras_config.txt)

I am running Java 1.8.0_66-b18.  If you need more info then please let me know.

Any help or workaround appreciated.

**Comment by nvonop** [comment]
The txt files are the generated config files.  It wouldn't let me attach them in JSON format.

**Comment by smccarthy** [comment]
I'll look at this. What version of Grid Extras are you using? @nvonop 

I see it gets created here https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/GridStarter.java#L173

I can try your exact first time run config options to see if I can reproduce.

**Comment by smccarthy** [comment]
I reproduced this with 1.12.7 . My guess is that https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/GridStarter.java#L125 is returning 0 config files. I will have to do some debugging tho

**Comment by smccarthy** [comment]
@nvonop I actually see node_5555.bat is getting created. Are you seeing something else ?

**Comment by nvonop** [comment]
Sorry for the slow response. I was running 1.2.4 on Windows 7 64.

**Comment by nvonop** [comment]
Also, to confirm, I was not even getting a bat file created following the initial configuration questions.

**Comment by smccarthy** [comment]
@nvonop can you try 1.12.7 ?

**Comment by nvonop** [comment]
Sure. Will try today and confirm.

**Comment by nvonop** [comment]
This seems to be resolved in 1.12.7.  Thanks for taking a look.  Will close the issue.
