### ISSUE TITLE
Option 3 Node+Hub missing prompt for number of tests before restarting

### ISSUE THREAD

**Issue by endqwerty** [groupon/Selenium-Grid-Extras#274]
When running as a node, there is a prompt for after how many tests should the machine restart. However, this prompt is skipped over when running as Hub+Node. This results in the default 10 test executions before restarting. The option can be manually inserted into the selenium_grid_extras_config.json

**Comment by smccarthy** [comment]
We don't want to allow the hub and node to restart I believe. It might default to 10,but I don't think it restarts these machines.

If the hub restarts it will affect every node that is running tests

**Comment by smccarthy** [comment]
@endqwerty Does this answer your question ( you should not be allowed to restart a machine if you choose `hub` or `hub+node`) ?

**Comment by smccarthy** [comment]
Closing. Non-issue
