### ISSUE TITLE
Reboot after sessions doesn't work 

### ISSUE THREAD

**Issue by kqiang** [groupon/Selenium-Grid-Extras#277]
I am using the latest version of Selenium-Grid-Extras. We set it to reboot our Windows VMs after 15 testing sessions, but it didn't reboot the Windows VMs. This feature was working before. Are there any new changes into this area which requires new settings for this feature?

Cheers,
Kewei

**Comment by smccarthy** [comment]
Is it a hub and node? or just node ? If it is a hub and node, it won't reboot.

**Comment by kqiang** [comment]
It is node only. I have the following settings right now in the config file:
"reboot_after_sessions": "15",
"enable_session_hitory": "1",

**Comment by kqiang** [comment]
This is the config file we have. It used to work with this config. Now I tried to add "enable_session_hitory": "1", but it still didn't work.

{
  "theConfigMap": {
    "auto_update_browser_versions": "0",
    "hub_config_files": [],
    "auto_start_hub": "0",
    "iedriver": {
      "version": "2.48.0"
    },
    "default_role": "node",
    "chromedriver": {
      "version": "2.24"
    },
    "auto_update_drivers": "0",
    "video_recording_options": {
      "videos_to_keep": "10"
    },
    "auto_start_node": "1",
    "hub_config": {},
    "log_maximum_age_ms": 864000000,
    "reboot_after_sessions": "15",
    "webdriver": {
      "version": "2.48.2"
    },
    "node_config_files": [
      "node_5555.json"
    ]
  }
}

**Comment by smccarthy** [comment]
@kqiang Can you let me know what OS you are using ? Also, what version of Selenium-Grid-Extras ? I'll try to reproduce this week.

**Comment by kqiang** [comment]
We tried the latest version, it started working now. We can close this issue.

Regards,
Kewei


On Dec 4, 2016, at 9:02 PM, Shawn McCarthy <notifications@github.com<mailto:notifications@github.com>> wrote:


@kqiang<https://github.com/kqiang> Can you let me know what OS you are using ? Also, what version of Selenium-Grid-Extras ? I'll try to reproduce this week.

-

**Comment by smccarthy** [comment]
Thanks for checking. Closing.
