### ISSUE TITLE
Invalid initial heap size on extras 1.12.7

### ISSUE THREAD

**Issue by ethan-eb** [groupon/Selenium-Grid-Extras#281]
We tried to move from 1.11.8 to 1.12.7 today. We've been having inconsistent test results on 1.11.8, and we're not sure this will help, but we decided to try.

Also went from firefox 42.0 to 44.0

We run the grid on Ubuntu 14.04 in AWS. Supervisor is the process manager we use to execute the extras jar.

On both nodes and hub supervisor was was able to run the main extras jar without error, but in the grid_extras log we got:

     command: /usr/lib/jvm/jdk1.8.0_91/jre/bin/java -Xms256m -Xmx4g -DPOOL_MAX=1024  -cp /usr/share/selenium-extras/SeleniumGridExtras-1.12.7-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.1.jar org.openqa.grid.selenium.GridLauncher -role hub -log log/hub_4444.log -hubConfig hub_4444.json
     exit code: 1
     standard error:
     Invalid initial heap size: -Xms256m -Xmx4g -DPOOL_MAX=1024
    Error: Could not create the Java Virtual Machine.
    Error: A fatal exception has occurred. Program will exit.

I don't believe there is actually a problem with initial heap size, that config didn't change (I have "grid_jvm_x_options": "-Xms256m -Xmx4g -DPOOL_MAX=1024"), and it's the same instance. But I was not able to determine the issue. 

I was actually able to run the command printed there manually, and it worked.

Any ideas?

**Comment by smccarthy** [comment]
Do you get this error on 1.12.2 ? I know with one of the recent version (1.12.4 - 1.12.7), we did some changes around generating the hub and node commands. We now use a String array with Runtime.getRuntime().exec() (instead of String).

**Comment by smccarthy** [comment]
@ethan-eb I think I fixed this in master. Can you perhaps build from master ( mvn clean install -DskipTests ), and try this out? I don't know when I'll have time to check myself. If you tell me this works, I will create a new build.

Thank you.

**Comment by ethan-eb** [comment]
Yes! that works! If you could make a build with that change it would be great, thanks!

**Comment by smccarthy** [comment]
https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.8

@ethan-eb Please try this release.

**Comment by smccarthy** [comment]
Marking as closed. Please re-open if still an issue. Thank you.

@ethan-eb
