### ISSUE TITLE
selenium grid extra removed configuration section and servlet ssection when used with selenium 3.0

### ISSUE THREAD

**Issue by shankarkc** [groupon/Selenium-Grid-Extras#286]
Summary : - config tag and servlet tag get removed when selenium 3.0 used once grid extra starts running

![screen shot 2016-12-14 at 3 55 44 pm](https://cloud.githubusercontent.com/assets/4651863/21178676/aadd052a-c216-11e6-8bdc-1dba095c750b.png)
I am using selenium grid extra with below config files

Before running selenium grid extra content of node_5555.json was
```
{
  "capabilities": [
  {
    "browserName": "firefox",
    "extension.sikuliCapability": true,
    "maxInstances": 1,
    "version": "50.0",
    "platform": "LINUX",
    "seleniumProtocol": "WebDriver"
  },
  {
    "browserName": "chrome",
    "extension.sikuliCapability": true,
    "maxInstances": 1,
    "version": "55.0.2883.87",
    "platform": "LINUX",
    "seleniumProtocol": "WebDriver"
  }
],
  "configuration": {
	  "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
          "servlets": "io.sterodium.extensions.node.SikuliExtensionServlet,io.sterodium.extensions.node.upload.FileUploadServlet,io.sterodium.extensions.node.download.FileDownloadServlet",
	  "maxSession": 1,
          "host": cda467ebd027,
	  "port": 5555,
	  "register": true,
	  "unregisterIfStillDownAfter": 10000,
	  "hubPort": 7777,
	  "hubHost": SeleniumHub ,
	  "nodeStatusCheckTimeout": 10000,
	  "downPollingLimit": 0
  }
}
```

Command used to run selenium grid extra was
```
xvfb-run -n 99 --server-args=-screen 0 1600x900x24 -ac +extension RANDR java -jar /opt/selenium_ex/SeleniumGridExtras-jar-with-dependencies.jar -Xmx=1250m
```

Once grid starts running content of json was
```
{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "extension.sikuliCapability": true,
      "browserName": "firefox",
      "maxInstances": 1,
      "version": "50.0",
      "platform": "LINUX"
    },
    {
      "seleniumProtocol": "WebDriver",
      "extension.sikuliCapability": true,
      "browserName": "chrome",
      "maxInstances": 1,
      "version": "55.0.2883.87",
      "platform": "LINUX"
    }
  ],
  "loadedFromFile": "node_5555.json",
  "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "unregisterIfStillDownAfter": 10000,
  "hubPort": 7777,
  "hubHost": "SeleniumHub",
  "host": "cda467ebd027",
  "nodeStatusCheckTimeout": 10000,
  "downPollingLimit": 0
}
```
Notice that 1) config section vanishes 2) servlet section too missing
Instead of config there is an extra tag in node_5555.json as shown below
```
"loadedFromFile": "node_5555.json",
```
Please fix. This is a blocker to use selenium 3.0

**Comment by shankarkc** [comment]
In GridNode.java you missed get/setServlet section. We leverage on sikuli extenstion for UI automation. Is its not hadled in selenim 3.0 code servlet section get removed
```
 "servlets": "io.sterodium.extensions.node.SikuliExtensionServlet,io.sterodium.extensions.node.upload.FileUploadServlet,io.sterodium.extensions.node.download.FileDownloadServlet",
```
Please fix. Though SeleniumGridExtra might not be using servlet users still may use it for some other purpose. So pls retain it.  Also pls add some documentation on how the json file config differs in selenium 3.0

**Comment by smccarthy** [comment]
The removal of the configuration section is on purpose. Selenium 3.0 removed it to make the config file neater (I don't know the real reason, but that's my guess). 

`loadedFromFile` has always been in the config file, if you are using selenium grid extras.

The removal of the servlets method was my fault, I am sorry. When someone upgrades from 2.0 to 3.0, I grab each of the existing values that grid extras sets, and puts it into the new format. I didn't take into account extra items that users could have added. I can try and take a look at this sometime soon, but it might be a week or two (I'm pretty busy at work and with life stuff). I don't think it will affect you if you are staying on 3.0, if you wanted to add it back manually.

**Comment by smccarthy** [comment]
@shankarkc Sorry but things have been really hectic in my life and day job. I don't know when I'll be able to get to this. It is on my radar, and when things do calm down, I can work on it.

**Comment by shankarkc** [comment]
Hi Can you pls fix it?

**Comment by shankarkc** [comment]
@smccarthy  can you pls review my pull request and merge it if you find it OK.
Here is the pull request.
https://github.com/groupon/Selenium-Grid-Extras/pull/349

**Comment by smccarthy** [comment]
@shankarkc Thank you. I merged it. I'll make a new release at some point today.

**Comment by shankarkc** [comment]
I am closing this defect as its fixed by https://github.com/groupon/Selenium-Grid-Extras/pull/353
