### ISSUE TITLE
Hub and node config script doesn't prompt for "restart after X tests", defaults to 10

### ISSUE THREAD

**Issue by mlapierre** [groupon/Selenium-Grid-Extras#289]
If I select option 3 (hub & node) as the role when running the first config I don't get prompted to specify after how many tests to restart. The config defaults to 10 (as shown by /config), but I'd prefer it disabled. I've set it manually to 0 but I'm reporting it because it seems like a bug in the config script.

If I select option 1 (node only) then it asks `Restart after how many tests (0-never restart)`. But if I select option 3 it doesn't ask that question and goes straight to `Would you like this user to automatically log in after restart (1-yes/0-no)`.

OS: Windows Server 2012 R2
Extras version: 1.12.9-SNAPSHOT

**Comment by smccarthy** [comment]
I merged in #290
