### ISSUE TITLE
Need option to disable marionette

### ISSUE THREAD

**Issue by mlapierre** [groupon/Selenium-Grid-Extras#296]
Marionette is [not yet feature-complete](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status). It breaks on many of my tests that work find on the legacy firefox driver. E.g.:

`org.openqa.selenium.UnsupportedCommandException: POST /session/be01de5f-33ba-475c-b963-eecc7d320909/keys did not match a known command`

It can be disabled so that selenium standalone uses the legacy firefox driver by setting:

`webdriver.firefox.marionette=false`

It would be useful if there were a way to configure Extras to generate node startup scripts with that property set, instead of setting `webdriver.gecko.driver`

**Comment by vveliev** [comment]
You can pass this as compatibility from client side  
marionette: false

**Comment by mlapierre** [comment]
Ahh, so you can. In that case I'll close this.

**Comment by vveliev** [comment]
I think you should reopen this ticket. 

as some options are ignored .....

```
"Dwebdriver.firefox.bin=/opt/firefox/firefox-bin": "",
```

not working as well ....

**Comment by vveliev** [comment]
maybe something to do with this http://stackoverflow.com/questions/16558709/gson-issue-with-string

**Comment by mlapierre** [comment]
Yeah you're right, it would be better to have the option of passing any of those types of options.

**Comment by vveliev** [comment]
I opened #298

**Comment by smccarthy** [comment]
@vveliev @mlapierre Closing this issue, since #298 is open. For marionette, you would set this on the client side, like others have mentioned. Selenium Grid Extras will add the geckodriver to the classpath, but as long as you set the marionette capability to false, you won't be using geckodriver.

Hope this helps!
