### ISSUE TITLE
GRID | Node should register on the grid in form of http://{host}:{port}

### ISSUE THREAD

**Issue by mstankovic86** [groupon/Selenium-Grid-Extras#299]
This issue blocks me to switch on selenium 3. I was thinking that is selenium issue but it is not.
see https://github.com/SeleniumHQ/selenium/issues/3385 for details.

When I create a NODE using SGE, my NODE is connected on the HUB with friendly name instead of url of the remoteHost, and because of that only one NODE is able to connect on the HUB

there is a part of my node_5555.json file created by SGE

"loadedFromFile": "node_5555.json",
"proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
"maxSession": 3,
"port": 5555,
"register": true,
"unregisterIfStillDownAfter": 10000,
"hubPort": 4444,
"hubHost": "172.16.2.79",
"registerCycle": 5000,
"nodeStatusCheckTimeout": 10000,
"downPollingLimit": 0

so without "id" config property but for some reason it is connected with id="friendlyNameOfMyComputer"

![screen shot 2017-01-19 at 11 31 07 am](https://cloud.githubusercontent.com/assets/8803779/22329744/0568d032-e3c3-11e6-93dd-f05f1ac91299.png)

when I use selenium-server-standalone-3.0.1.jar to setup GRID, all NODES are connected since they are connected without specified "id" property. 

![screen shot 2017-01-26 at 12 00 11 pm](https://cloud.githubusercontent.com/assets/8803779/22329882/a3d35fd0-e3c3-11e6-80db-88f1ae0df515.png)

Please HELP!

**Comment by smccarthy** [comment]
I will try and look at this this weekend.

**Comment by smccarthy** [comment]
@mstankovic86 The code to be fixed is here I believe : https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/GridStarter.java#L227-L234

**Comment by smccarthy** [comment]
It looks like with selenium3, we do NOT use friendlyHostName. What version of Selenium Grid Extras are you on?

**Comment by smccarthy** [comment]
Oh, It looks like it is fixed on master. I will make a release tonight or tomorrow at the latest. Sorry for taking awhile.

**Comment by smccarthy** [comment]
@mstankovic86 I made a new release, v1.12.10  . Please try it and let me know. Thanks.

**Comment by mstankovic86** [comment]
@smccarthy YES! it works! Thanks a lot. You can close this issue. thanks again
