### ISSUE TITLE
java Precondition error with version 1.12.11

### ISSUE THREAD

**Issue by taren7** [groupon/Selenium-Grid-Extras#316]
I recently downloaded the latest version of selenium grid extras (1.12.11). Now I get this exception while initializing the browser:
com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V

Does anyone have a solution?

**Comment by taren7** [comment]
I finally got it working by changing the Web driver version to 3.0.1 instead of 3.0.1

**Comment by Mjl33** [comment]
This is related to https://github.com/SeleniumHQ/selenium/issues/3596

**Comment by smccarthy** [comment]
@Mjl33 Thanks for the suggestion. Is this a change to the Selenium-Grid-Extras project? Or the client side of things? Just checking if we need to fix anything on our (Selenium-Grid-Extras) side. Thanks again.

**Comment by taren7** [comment]
I think the dependency should be updated on (Selenium-Grid-Extras) side.

**Comment by smccarthy** [comment]
Thanks. I'll make a new release tonight with that dependency bumped.

**Comment by smccarthy** [comment]
@taren7 @Mjl33  Please try with https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.12

**Comment by Mjl33** [comment]
@smccarthy its working with https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.12

**Comment by smccarthy** [comment]
Closing as this is verified fixed.
