### ISSUE TITLE
Unregistering the node http://xxx.xxx.xxx.xxx:5555 because it's been down for xxxxx milliseconds

### ISSUE THREAD

**Issue by algorithminflux** [groupon/Selenium-Grid-Extras#317]
After Node successfully registers with Hub, the following is logged in the Hub's hub_xxxx.log file:

> 16:01:37.518 INFO - Registered a node http://192.168.28.238:5555
> 16:01:42.684 INFO - Marking the node http://192.168.28.238:5555 as down: cannot reach the node for 1 tries
> 16:01:52.699 INFO - Unregistering the node http://192.168.28.238:5555 because it's been down for 10015 milliseconds
> 16:01:52.699 WARN - Cleaning up stale test sessions on the unregistered node http://192.168.28.238:5555
> 16:01:57.583 INFO - Registered a node http://192.168.28.238:5555
> 16:02:02.591 INFO - Marking the node http://192.168.28.238:5555 as down: cannot reach the node for 1 tries
> 16:02:12.605 INFO - Unregistering the node http://192.168.28.238:5555 because it's been down for 10014 milliseconds
> 16:02:12.605 WARN - Cleaning up stale test sessions on the unregistered node http://192.168.28.238:5555
> 16:02:12.630 INFO - Registered a node http://192.168.28.238:5555
> 16:02:17.637 INFO - Marking the node http://192.168.28.238:5555 as down: cannot reach the node for 1 tries
> 16:02:27.652 INFO - Unregistering the node http://192.168.28.238:5555 because it's been down for 10014 milliseconds
> 16:02:27.652 WARN - Cleaning up stale test sessions on the unregistered node http://192.168.28.238:5555

The Node is registered with the Hub at 16:01:37, but then it goes down according to the Hub at 16:01:42, 5 seconds later. It continues this pattern indefinitely until I manually bring the Node down.

For reference, this happens with all 4 of my Nodes (Win10, Win7, Win8_1, Mac). They're all on the same LAN (i.e. 192.168.28.xxx).

I don't believe this used to happen on previous SeleniumGridExtras versions. I upgraded my Hub and Nodes to 1.12.12 this morning.

**Comment by smccarthy** [comment]
I think someone added a change around that area in one of the recent releases. Do you know what version you were on before, where it worked correctly ?

**Comment by algorithminflux** [comment]
I believe it was SeleniumGridExtras 1.12.10.

**Comment by algorithminflux** [comment]
I was also using WebDriver 3.0.1 for awhile, so I'll be testing different WebDriver versions as well to see if that may be the culprit.

**Comment by algorithminflux** [comment]
I should clarify that I'm using WebDriver 3.3.0 right now, and that I'm going to try testing the entire ecosystem using WebDriver 3.0.1 with the latest SeleniumGridExtras (1.12.12).

**Comment by algorithminflux** [comment]
Using WebDriver 3.0.1 and SeleniumGridExtras 1.12.12, I was not able to reproduce the issue, so it would seem that the issue is with the WebDriver, between WebDriver versions 3.0.1 and 3.3.0.

**Comment by smccarthy** [comment]
Thanks for the quick check here and closing this.

**Comment by OleksandrPolazhynets** [comment]
Hi, do you have link to particular WebDriver issue ? Thanks!

**Comment by algorithminflux** [comment]
Hi OleksandrPolazhynets! No, I don't have a link to a particular WebDriver issue. I did notice that someone else noticed a similar, if not identical issue on here.

https://github.com/groupon/Selenium-Grid-Extras/issues/318
