### ISSUE TITLE
Issues with Node Registration (PROXY_REREGISTRATION)

### ISSUE THREAD

**Issue by smattt** [groupon/Selenium-Grid-Extras#318]
We moved to the latest release v1.12.12 recently and everything worked great the first two days but now we're plagued with PROXY_REREGISTRATION errors that I can't seem to resolve. There is very little information online about this particular error code.

In the hub logs, I see a lot of activity - registering nodes and cleaning up _stale_(?) node sessions:

`02:30:49.003 INFO - Unregistering the node http://xxx.xxx.182.128:5551 because it's been down for 10015 milliseconds
02:30:49.003 WARN - Cleaning up stale test sessions on the unregistered node http://xxx.xxx.182.128:5551
02:30:49.050 INFO - Registered a node http://xxx.xxx.182.128:5551
02:30:49.972 INFO - Registered a node http://xxx.xxx.58.224:5550
02:30:52.372 INFO - Unregistering the node http://xxx.xxx.30.73:5552 because it's been down for 10022 milliseconds
02:30:52.372 WARN - Cleaning up stale test sessions on the unregistered node http://xxx.xxx.30.73:5552
02:30:52.419 INFO - Registered a node http://xxx.xxx.30.73:5552
02:30:54.053 INFO - Marking the node http://xxx.xxx.182.128:5551 as down: cannot reach the node for 1 tries
02:30:54.976 INFO - Marking the node http://xxx.xxx.58.224:5550 as down: cannot reach the node for 1 tries
02:30:57.431 INFO - Marking the node http://xxx.xxx.30.73:5552 as down: cannot reach the node for 1 tries`

I bumped up the hub's cleanUpCycle to 10s and that seemed to help a bit, but not enough.

In Selenium Grid's console UI, each of my nodes shows this possibly related error message:

> SetupTeardownProxy unknown version,server response code : 500

It appears that each node successfully registers with the hub, then 5 seconds later they are marked as down (probably due to the SetupTeardownProxy HTTP 500), and finally 10 seconds later the node is removed from the hub's list of registered nodes... and the cycle repeats as the node attempts to re-register.

This is the error I'm seeing in my test runner (Visual Studio Team Services / Visual Studio Test Runner):

> System.InvalidOperationException: Session [87a9dff5-aeba-4a15-b36c-64276527ef38] was terminated due to PROXY_REREGISTRATION

I'm using WebDriver 3.3.0 on all hubs and nodes, with Selenium Grid Extras v1.12.12.

Thank you

**Comment by smattt** [comment]
On a related note, my grid_extras hub log included these events:

> 09 Mar 2017 03:10:00 [qtp1891546521-24] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.58.224:5550
09 Mar 2017 03:10:02 [qtp1891546521-26] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.30.73:5552
09 Mar 2017 03:10:07 [qtp1891546521-19] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.182.128:5551
09 Mar 2017 03:10:15 [qtp1891546521-26] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.58.224:5550
09 Mar 2017 03:10:17 [qtp1891546521-22] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.30.73:5552
09 Mar 2017 03:10:22 [qtp1891546521-22] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.182.128:5551
09 Mar 2017 03:10:32 [qtp1891546521-26] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.30.73:5552
09 Mar 2017 03:10:35 [qtp1891546521-26] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.58.224:5550
09 Mar 2017 03:10:37 [qtp1891546521-19] INFO  proxies.SetupTeardownProxy  - Attaching node http://xxx.xxx.182.128:5551

**Comment by Mjl33** [comment]
There is a compatibility issue with Grid Extras v1.12.12 and WebDriver 3.3.0 where the Proxy version is not recognized

You need to bump down WebDriver to 3.2.0

**Comment by smattt** [comment]
You are the man, thank you for saving me a ton of time! :)

**Comment by smccarthy** [comment]
I wonder if its a grid extras issue, or if its a selenium grid issue in general.

**Comment by alltheoptions** [comment]
+1

**Comment by smccarthy** [comment]
@alltheoptions Hi, what is the +1 for ?

**Comment by alltheoptions** [comment]
@smccarthy the problem still exists
