### ISSUE TITLE
How to change role?

### ISSUE THREAD

**Issue by qaquest** [groupon/Selenium-Grid-Extras#325]
Hi, thx for Selenium-grid-extras...nice stuff.
1. Once the jar is run on a machine as a Hub, how can it be updated to be used as a Hub & Node.
2. How to unregister a Hub?

**Comment by shankarkc** [comment]
delete the seleniumgridextra.json and node json file. rerun the jar. it will tae u throught he wizards again.

**Comment by smccarthy** [comment]
Since @shankarkc answered the question, closing this out. Please re-open if it doesn't work for you @qaquest .
