### ISSUE TITLE
Windows documentation clairy

### ISSUE THREAD

**Issue by andytsnowden** [groupon/Selenium-Grid-Extras#335]
Hello,

I recently spent a bit of time trying to get this to run on my windows 2012r2 box and was constantly getting `Error: Could not find or load main class XXXXX`.

After searching google and this github I finally noticed my specific error `Error: Could not find or load main class "Selenium"` matched the partial name of my path I had downloaded the jar to `C:\Program Files\Selenium Grid\`.  on a hunch I removed the space from Selenium Grid and my error changed to `Error: Could not find or load main class "Files"`.

Please update your README to mention the path on windows can not have any spaces or the node will fail to start.  Alternatively you might see if this is a bug worth fixing.  It's more QoL than anything but it still caused me to waste a bunch of time.

**Comment by smccarthy** [comment]
Thank you for catching this. I updated the README. I don't have much time nowadays to make bug fixes, but I can review and merge in any PRs that come along. Closing this since README is updated in master.
