### ISSUE TITLE
Force 32-bit Internet Explorer driver

### ISSUE THREAD

**Issue by pgardella** [groupon/Selenium-Grid-Extras#336]
Is there a way to force the version of IEDriver which gets downloaded so it always runs the 32bit version?

There is a [common problem](http://stackoverflow.com/questions/8850211/why-is-selenium-internetexplorerdriver-webdriver-very-slow-in-debug-mode-visual) with the 64bit IEDriver which causes extremely slow typing. The recommended answer is to force the use of the 32bit IEDriver. But with SeleniumGridExtras doing the work of downloading the driver, how can I tell it use the 32bit version only?

**Comment by smccarthy** [comment]
It should ask you what bit you want (or maybe it doesn't and just assumes 32bit). Are you noticing that it is downloading 64 bit without asking you when you ran the initial setup ?

**Comment by pgardella** [comment]
Well now, my apologies. I thought for sure I checked that.  It looks like it was set to 64bit (by default) when I ran the installer, and I neglected to change it to 32. And then, since I'm storing the configuration on the hub, any time I changed it locally, it reverted back to what it was from the hub (which is why it has that big warning message at the top of the config file!).
