### ISSUE TITLE
GridNode loadFromFile ignores custom config.

### ISSUE THREAD

**Issue by lenny1806** [groupon/Selenium-Grid-Extras#342]
The method [loadFromFile ](https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/config/GridNode.java#L102) ignores the Field **custom** in the _nodeConfig.json_. As it is a supported field by default (see [DefaultNodeWebDriver.json](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json)) in Selenium3 it should be supported and not get deleted when loading the _nodeConfig.json_.

I can provide a pull request if you wish. 

Cheers

**Comment by vipin0060** [comment]
Hi, i am also facing this issue. Can you provide me a fix for this ?

**Comment by lenny1806** [comment]
@vipin0060 see my commit and pull request.
