### ISSUE TITLE
How to run sikuli with groupon/Selenium-Grid-Extras?

### ISSUE THREAD

**Issue by misko-frame** [groupon/Selenium-Grid-Extras#346]
I am having troubles configuring & starting grid&node **with Sikuli support**, so any advice how to overcome this issue will be much appreciated.

This is my current setup ( _created from instructions for sterodium/selenium-grid-extensions_)
-Test machine I am currently using is: MAC (macOS Sierra, Version 10.12.5)
-My current **_grid configuration_**:
GRID.json
{
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : ["io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet"],
  "withoutServlets": [],
  "custom": {},
  "capabilityMatcher": "io.sterodium.extensions.capability.CustomCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "cleanUpCycle": 5000,
  "role": "hub",
  "debug": false,
  "browserTimeout": 0,
  "timeout": 1800
}

-My current **_node configuration_**:
{
  "capabilities":
  [
    {
      "extension.sikuliCapability": true
    },
    {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 2,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hubPort":4444,
        "hubHost":"localhost",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : ["io.sterodium.extensions.node.SikuliExtensionServlet","io.sterodium.extensions.node.upload.FileUploadServlet","io.sterodium.extensions.node.download.FileDownloadServlet"],
  "withoutServlets": [],
  "custom": {}
}

**Start grid command**:
cd $(dirname "$0")
java -cp "selenium-server-standalone-3.3.1.jar:extension-proxy-0.6.jar" org.openqa.grid.selenium.GridLauncherV3 -role hub -hubConfig GRID.json

**Start node command**:
cd $(dirname "$0")
java -cp "selenium-server-standalone-3.3.1.jar:extension-proxy-0.6.jar:all-node-extensions-0.6.jar" org.openqa.grid.selenium.GridLauncherV3 -role node -nodeConfig NODE.json

**_Grid directory contains_**:
chromedriver_mac64
extension-proxy-0.6.jar
selenium-server_standalone-3.3.1.jar
start_grid._MAC.command
GRID.json

_**Node directory contains**_:
chromedriver_mac64
extension-proxy-0.6.jar
all-node-extensions-0.6.jar
selenium-server_standalone-3.3.1.jar
start_node._MAC.command
NODE.json

I have read instructions for "generating" GRID groupon/Selenium-Grid-Extras/

After generating action, I have tried to modify config files, tried to add extension-proxy-0.6.jar,
all-node-extensions-0.6.jar to Grid directory etc... with no success.

Could anyone suggest how to generate/configure GRID&NODE, how to start services after that in order to use groupon/Selenium-Grid-Extras with Sikuli extension?

THANK YOU VERY MUCH,
Milos

**Comment by smccarthy** [comment]
https://github.com/groupon/Selenium-Grid-Extras/issues/223#issuecomment-224199500
or 
https://github.com/groupon/Selenium-Grid-Extras/search?q=sikuli&type=Issues&utf8=%E2%9C%93

I have seen people use sikuli with Grid Extras. Please see those issues that mention it.

**Comment by shankarkc** [comment]
@misko-frame  its easy
can you pls refer the answer here from me ?
https://github.com/groupon/Selenium-Grid-Extras/issues/315
Its working fine for me. I prefer to use Linux OS for it

**Comment by smccarthy** [comment]
Closing this out since the solution was mentioned.
