### ISSUE TITLE
Upgrade to 1.12.13 broken (must re-configure)

### ISSUE THREAD

**Issue by mikesalvia** [groupon/Selenium-Grid-Extras#348]
Version: 1.12.13
Previous Version: 1.12.12

After upgrading to 1.12.13 I am receiving:

`Exception in thread "main" java.lang.NullPointerException
	at com.groupon.seleniumgridextras.config.GridNode.loadFromFile(GridNode.java:138)
	at com.groupon.seleniumgridextras.config.Config.loadNodeClasses(Config.java:120)
	at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfig.java:152)
	at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:70)`

Apparently, `1.12.13` is unable to locate and read my `1.12.12` configuration files.

I am not sure where or how, logs weren't very helpful, but re-configuring through `1.12.13` did work.

**Comment by smccarthy** [comment]
@mikesalvia Do you still have your 1.12.12 configuration ? I can take a look and try and get out a quick patch.

**Comment by smccarthy** [comment]
I noticed line 138 is:
` configFromFile = topLevelJson.getAsJsonObject("configuration").toString();` (this is/should be called if you are using selenium 3, but the configuration file is in the selenium 2 format). Is that your case?

**Comment by smccarthy** [comment]
I tried doing a compare of the 1.12.12 and 1.12.13 configs (with the choices I choose), and I see this :
https://gist.github.com/smccarthy/3fb2e9b3c48cb0f963adcdffb9ce452d

The differences I see are that the `node_5555.json` config added ` "custom": {},`. The qselenium_grid_extras_config.json` added the geckodriver bitness. I think its the node_5555.json that is the issue, but don't know why yet.

**Comment by mikesalvia** [comment]
@smccarthy Sorry but I had destroyed them to reset Selenium Grid Extras checking Trash right now.

**Comment by mikesalvia** [comment]
### node_5555.json in 1.12.12
`{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 1,
      "version": "53",
      "platform": "MAC"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "maxInstances": 1,
      "version": "57",
      "platform": "MAC"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "safari",
      "maxInstances": 0,
      "version": "",
      "platform": "MAC"
    }
  ],
  "loadedFromFile": "node_5555.json",
  "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "unregisterIfStillDownAfter": 10000,
  "hubPort": 4444,
  "hubHost": "192.168.20.32",
  "registerCycle": 5000,
  "nodeStatusCheckTimeout": 30000,
  "downPollingLimit": 20
}`

### selenium_grid_extras_config.json in 1.12.12
`{
  "theConfigMap": {
    "auto_update_browser_versions": "0",
    "hub_config_files": [],
    "auto_start_hub": "0",
    "iedriver": {
      "version": "3.4.0"
    },
    "default_role": "node",
    "unregisterNodeDuringReboot": "false",
    "chromedriver": {
      "bit": "64",
      "version": "2.31"
    },
    "auto_update_drivers": "1",
    "video_recording_options": {
      "record_test_videos": "false"
    },
    "auto_start_node": "1",
    "hub_config": {},
    "geckodriver": {
      "version": "0.18.0"
    },
    "log_maximum_age_ms": 8.64E8,
    "reboot_after_sessions": "0",
    "grid_extras_port": "3000",
    "webdriver": {
      "version": "3.4.0"
    },
    "grid_jvm_x_options": "-Xmx4g -XX:ParallelGCThreads\u003d12",
    "node_config_files": [
      "node_5555.json"
    ]
  }
}`

**Comment by smccarthy** [comment]
Thank you ! This will help me figure out a solution. I get the same error as you, with your config.

**Comment by smccarthy** [comment]
@mikesalvia Got it I think. I fixed it in 1.12.14 , with this commit . https://github.com/groupon/Selenium-Grid-Extras/commit/a1ec63f07c0a08b67fec16b2ea1a4d9665f25d2a

**Comment by smccarthy** [comment]
Closing. Please reopen if someone sees this as an issue again.
