### ISSUE TITLE
Selenium Grid Extras NOT compatible with Selenium 3.5.0  (even after reconfiguration)

### ISSUE THREAD

**Issue by mikesalvia** [groupon/Selenium-Grid-Extras#355]
Not sure what to add here... It is broken... And I mean completely broken reconfiguration will not work... I am attempting to rollback to 1.12.13 with 3.4.0 but seems quite difficult.

I restarted Selenium Grid Extras which automatically updated me to 3.5.0 and suggested I should install 1.12.15 so I did... And now all of my Selenium Nodes appear with status code 500 where I would expect to a version #.

The nodes constantly are removed and re-registered... This looks to be an issue with Selenium 3.5.0 and I have since rolled-back.

I am suggesting a SEPARATE configuration setting which will determine if Selenium Web Driver should be automatically updated vs. browser drivers (chromedriver, geckodriver, etc.)

The model of updating to a newly release version of WebDriver immediately seems that there is a lot of potential to cause race conditions as APIs of Selenium change, on the other hand updating geckodriver and other drivers that may receive updates in between Selenium release would be helpful.

EDIT: After more review the version of SeGridExtras doesn't matter, it is the compatibility of SeGridExtras with Selenium 3.5.0.

**Comment by Amber2008** [comment]
I hit the same problem

**Comment by Amber2008** [comment]
Do you know how to resolve this issue?
Or how to roll back to Selenium 3.3.0 ?

**Comment by Amber2008** [comment]
Do you know how to solve this issue?
@Shawn Mccarthy

**Comment by mikesalvia** [comment]
@Amber2008 you can use this method but it will NOT let you use 3.5.0...

Open your extras config JSON file... Set auto_update_drivers to 0... Then set 3.5.0 to 3.4.0 or 3.3.0 depending on your desired version...

Then restart SeGridExtras.

OR alternatively, you can completely reconfigure and choose not to update the drivers automatically and will be prompted for versions.

**Comment by Amber2008** [comment]
@mikesalvia 
Thanks very much, it really did a great help for me.

**Comment by shankarkc** [comment]
@mikesalvia i think its something to do with selenium standalone jar. I too hit the same issue and opened a bug. Please check if your node log has the call stack similar to mine.
https://github.com/SeleniumHQ/selenium/issues/4495
```
[qtp489349054-13] INFO org.seleniumhq.jetty9.server.handler.ContextHandler.ROOT - org.openqa.selenium.remote.server.WebDriverServlet-291caca8: Initialising WebDriverServlet
[qtp489349054-13] WARN org.seleniumhq.jetty9.server.HttpChannel - /wd/hub/status
java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;
        at org.openqa.selenium.remote.server.AllHandlers.<clinit>(AllHandlers.java:52)
        at org.openqa.selenium.remote.server.WebDriverServlet.init(WebDriverServlet.java:83)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.seleniumhq.jetty9.servlet.ServletHolder.initServlet(ServletHolder.java:637)
        at org.seleniumhq.jetty9.servlet.ServletHolder.getServlet(ServletHolder.java:498)
        at org.seleniumhq.jetty9.servlet.ServletHolder.ensureInstance(ServletHolder.java:785)
        at org.seleniumhq.jetty9.servlet.ServletHolder.prepare(ServletHolder.java:770)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:530)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
```
WebDriverServlet initialization is failing in my case

**Comment by mikesalvia** [comment]
@shankarkc To confirm the standalone JARs work if connecting strict node to strict grid but it maybe with how Selenium Grid Extras is resolving versions that is the problem.

**Comment by shankarkc** [comment]
Thanks @mikesalvia,  i launched selenium grid 
 without using grid extra. Then i noticed grid hitting this issue without grid extra involvement. So i thought it is grid issue and not grid extra issue.

**Comment by Amber2008** [comment]
Selenium Gird extras 1.12.15 with selenium webdriver 3.4.0 is workable.
@shankarkc

**Comment by shankarkc** [comment]
Thanks @Amber2008 i know it works with 3.4.0 But i want 3.5.x as there are some bug fixes wrt Firefox mouse event handling.  It looks like i have to  wait till they rollout new version.  Today i saw they fixed code causing the issue.  But they haven't rolled out new build yet.

**Comment by sanghviharshit** [comment]
Same issue. I tried to use with 3.4.0 on ubuntu and Mac with no luck. Switched to using selenium server standalone jar directly. Will switch to Selenium Grid Extras when it supports latest version.

**Comment by mikesalvia** [comment]
3.4.0 will auto update to 3.5.0 on start you need to disable automatic updating.

**Comment by smccarthy** [comment]
I ran into this issue as well. Due to personal reasons, I am unable to look into this issue. If someone else creates a PR to fix it, I can review it, and do a quick smoke test, and merge it.

**Comment by sanghviharshit** [comment]
I tested with 1.12.17 and confirming the new version fixed this issue. Thanks @smccarthy

**Comment by mikesalvia** [comment]
@smccarthy I will test this out ASAP.

**Comment by shankarkc** [comment]
I used 1.12.17 with 3.6.0 and it worked fine for me.

**Comment by mikesalvia** [comment]
Closing. 3.6.0 works with latest version
