### ISSUE TITLE
Nodes are not displayed in grid console on selenium 3.7.1 

### ISSUE THREAD

**Issue by da-yaroslav-orel** [groupon/Selenium-Grid-Extras#377]
![image](https://user-images.githubusercontent.com/17005945/33007964-b32088f4-cdd9-11e7-9f56-796885ade4bb.png)

**Comment by iconner** [comment]
Yes - I have been having this same issue using the latest release out-of-the-box !! Glad it's not just me. The nodes will not register to the hub and report internal server error in the log.

**Comment by truncj** [comment]
Just saw the same issue this morning.. any workarounds?

**Comment by smccarthy** [comment]
I'm not sure, but is this the fix ? https://github.com/groupon/Selenium-Grid-Extras/pull/375 . I haven't had much time lately, but I can try and look at this later this week.

**Comment by shankarkc** [comment]
I am also hitting this on Ubuntu 16.
Here is the node log
```
12:05:20.514 INFO - Selenium Grid node is up and ready to register to the hub
12:05:20.520 DEBUG - Using the json request : {"class":"org.openqa.grid.common.RegistrationRequest","name":null,"description":null,"configuration":{"remoteHost":"http://172.17.0.1:5555","hubHost":"127.0.0.1","hubPort":4444,"id":"http://172.17.0.1:5555","capabilities":[{"browserName":"firefox","maxInstances":3,"platform":"LINUX","seleniumProtocol":"WebDriver","version":""},{"applicationName":"","browserName":"chrome","maxInstances":3,"platform":"LINUX","seleniumProtocol":"WebDriver","version":""}],"downPollingLimit":0,"hub":"http://localhost:4444","nodePolling":5000,"nodeStatusCheckTimeout":10000,"proxy":"com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy","register":true,"registerCycle":5000,"unregisterIfStillDownAfter":10000,"cleanUpCycle":null,"custom":{},"host":"172.17.0.1","maxSession":1,"servlets":[],"withoutServlets":[],"browserTimeout":120000,"debug":false,"jettyMaxThreads":null,"log":null,"port":5555,"role":"node","timeout":120000,"enablePassThrough":true}}
12:05:20.521 INFO - Starting auto registration thread. Will try to register every 5000 ms.
12:05:20.521 INFO - Registering the node to the hub: http://127.0.0.1:4444/grid/register
12:05:20.531 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
12:05:25.536 INFO - Registering the node to the hub: http://127.0.0.1:4444/grid/register
12:05:25.542 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
```

Surprisingly on hub i dont see any reported internal server error
```
12:30:16.060 DEBUG - Using class com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy
12:30:21.066 DEBUG - getting the following registration request  : {"class":"org.openqa.grid.common.RegistrationRequest","name":null,"description":null,"configuration":{"remoteHost":"http://172.17.0.1:5555","hubHost":"127.0.0.1","hubPort":4444,"id":"http://172.17.0.1:5555","capabilities":[{"browserName":"firefox","maxInstances":3,"platform":"LINUX","seleniumProtocol":"WebDriver","version":""},{"applicationName":"","browserName":"chrome","maxInstances":1,"platform":"LINUX","seleniumProtocol":"WebDriver","version":""}],"downPollingLimit":2,"hub":"http://localhost:4444","nodePolling":5000,"nodeStatusCheckTimeout":5000,"proxy":"com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy","register":true,"registerCycle":5000,"unregisterIfStillDownAfter":10000,"cleanUpCycle":null,"custom":{},"host":"172.17.0.1","maxSession":3,"servlets":[],"withoutServlets":[],"browserTimeout":120000,"debug":false,"jettyMaxThreads":null,"log":null,"port":5555,"role":"node","timeout":120000,"enablePassThrough":true}}
12:30:21.067 DEBUG - Using class com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy
```
This is a blocker to migrate to 3.7.x can someone pls lookinto fixing this?

**Comment by shankarkc** [comment]
This looks like a bug specific to selenium grid extra. If I just use plain selenium grid 3.7.1 it works fine. With selenium grid extra its broken.

**Comment by smccarthy** [comment]
The PR I mentioned above is the fix. However, it breaks 3.7.0 and earlier. I will put that fix in a 2.0.0 release sometime today or tomorrow.

**Comment by smccarthy** [comment]
Try this release please : https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v2.0.0

I updated the changelog to show that 2.0.0 is NOT compatible with selenium 3.7.0 or older. It will only work with 3.7.1 or newer. I'll add some logic in the next 1.13.0 release (today or tomorrow), that'll prevent people from bumping to 3.7.1 of selenium.

**Comment by smccarthy** [comment]
The final release is 2.0.1 for Selenium 3.7.1 and newer, and 1.12.18 for selenium 3.7.0 and older. I put in logic that prevents someone from using an incompatible version of grid extras with selenium.

**Comment by shankarkc** [comment]
Cool great Thanks @smccarthy I will let you know by Monday eod IST

**Comment by shankarkc** [comment]
Thanks a lot @smccarthy I tested v2.0.1
<https://github.com/groupon/Selenium-Grid-Extras/tree/v2.0.1> and it worked
fine for me. Now i see the nodes in console page.
Thanks
Shankar KC

**Comment by smccarthy** [comment]
Closing this as the fix has been released.
