### ISSUE TITLE
Browser sessions are not getting killed and stays indefinitely when the test is aborted in the middle

### ISSUE THREAD

**Issue by vignesh-paramasivam** [groupon/Selenium-Grid-Extras#378]
I have updated the grid extras from 1.12.6 to 1.12.17 and selenium from 2.53.1 to 3.7.0.

Usually, when i abort the test, the sessions created will get killled automatically, and the nodes will be freed up. Now after the upgrade, the browser sessions are not getting killed, and the grid console shows the node is still occupied.

**Comment by smccarthy** [comment]
@vignesh-paramasivam Is it a selenium grid extras issue? Can you please try with 1.12.6 with 2.53.1 and 3.7.0 ?
