### ISSUE TITLE
Cannot start multiple HUBs on the same machine

### ISSUE THREAD

**Issue by mstankovic86** [groupon/Selenium-Grid-Extras#41]
Hi, 

I have problem to start few hubs on the same machine. Here is my shell script:
![screen shot 2014-09-17 at 10 34 40 am](https://cloud.githubusercontent.com/assets/8803779/4300520/8984dd8c-3e45-11e4-904a-0baf4d188330.png)

When I try manually to start two HUBs on the same machine (on different ports) I got this error (log.out):
![screen shot 2014-09-17 at 10 47 48 am](https://cloud.githubusercontent.com/assets/8803779/4300685/67d1397c-3e47-11e4-9eb9-0720ee82a1ab.png)

node_5555.log:
![screen shot 2014-09-17 at 10 52 19 am](https://cloud.githubusercontent.com/assets/8803779/4300770/f97bfa1a-3e47-11e4-87e0-99aba4dd84f0.png)

I was able to do this with selenium-server-standalone.jar. So, is there some other way to start two HUBs on the same machine? 

Thanks in advance.

**Comment by smccarthy** [comment]
Closing this since #177 is merged in awhile ago.
