### ISSUE TITLE
Auto fix browser versions

### ISSUE THREAD

**Issue by dimacus** [groupon/Selenium-Grid-Extras#44]
Currently if version of the browser is set as int in the json file, it will make the capability matcher fail. Fix it so that this is corrected on it's own.

**Comment by smccarthy** [comment]
A browser version is always (I think ?) set now with : 
https://github.com/groupon/Selenium-Grid-Extras/pull/81

If browser version can't be detected, it uses an empty string : ""

Can this be closed ?

**Comment by smccarthy** [comment]
I think this can be completed, but wanted to be sure. @dimacus  ?

**Comment by smccarthy** [comment]
Closing this as #81 is in master.
