### ISSUE TITLE
Screenshots and video logs black

### ISSUE THREAD

**Issue by CupboardMonkey** [groupon/Selenium-Grid-Extras#54]
Occasionally (I haven't managed to figure out the exact conditions yet), running SGE on a VM node will record a black square. I think it's recording the wrong session (there tends to be a console and sometimes a remote user logged in). Is there a way to have it follow the active session? On the plus side, SGE is awesome.
Cheers

**Comment by dimacus** [comment]
@CupboardMonkey is this still an issue for you? I'm having a similar issue on my new grid and i think i have a theory, wanna ask you more questions

**Comment by CupboardMonkey** [comment]
@dimacus hey we seem to have resolved the issue. It seemed to occur when the graphics driver for the session stopped running (ie after a timeout or disconnected user whilst the software is still running) I'll try and think of anything else I can remember but any questions just fire away =] cheers

**Comment by dimacus** [comment]
In my case i've tracked it down to the use of RDP sessions to connect to the node. When you close the RDP session windows goes into a GUI-less mode and the screen goes black.

I've found a way to force the graphics mode to remain always on... if you use a tightvnc or any other server on the node and connect to the node with VNC protocol, the vnc server will keep the graphics on permanently and prevent this from happening.
