### ISSUE TITLE
Please add support for Appium iOS Safari Nodes

### ISSUE THREAD

**Issue by sahajamit** [groupon/Selenium-Grid-Extras#57]
At Present we also use Selenium Grid to run our scripts on appium Node for iPhone and iPad Safari. I would really appreciate if you can please add support for Appium nodes so that we can use grid-extras to manage our Appium nodes as well. We are using Appium's 0.18.x version.

This is the sample command which we use to start appium node:

appium -p 4730 --nodeconfig /Users/admin/Desktop/appiumgrid_iPad-Simulator1.json

And this is the sample json which we use:
{
    "capabilities": [
        {
            "browserName": "iPad-Simulator",
            "version": "7.1",
            "maxInstances": 1,
            "platform": "MAC"
        }
    ],
    "configuration": {
        "cleanUpCycle": 2000,
        "timeout": 300000,
	"browserTimeout": 60000,
        "hub": "http://XXX.20.10.XX:4444/grid/register",
	"host": "172.20.10.29",
        "maxSession": 1,
	"port": 4730,
	"hubPort": 4444,
        "hubHost": "XXX.20.10.XX",
        "url": "http://XXX.20.10.XX:4730/wd/hub",        
	"register": true,
	"registerCycle": 5000,
        "role": "node"
    }
}

**Comment by smccarthy** [comment]
@sahajamit This has been merged into master and a new release ( a few new releases actually ) have this. Closing this issue. Please re-open or open a new issue if you see any problems. Thank you.
