### ISSUE TITLE
Selenium Grid Extras not restarting after N tests

### ISSUE THREAD

**Issue by Ahskaniz** [groupon/Selenium-Grid-Extras#66]
Hi Dima, 

I'm running the last Grid Extras (v1.7.1) in a windows vm and in the configuration I set the restart of the vm at 10 tests.
Despite this, the vm is not restarting. In the logs there's no tracking information and I accumulate like 100+ sessions without a restart.
It seems not to be a browser bug related, because it fails for ie/chrome/firefox.

Thanks in advance

**Comment by smccarthy** [comment]
@Ahskaniz Is this fixed for you in Selenium-Grid-Extras 1.10.0 ?

**Comment by Ahskaniz** [comment]
@smccarthy I just stopped using this feature for one handmade.

**Comment by smccarthy** [comment]
@Ahskaniz Ok thanks for the quick response!

**Comment by smccarthy** [comment]
Closing as we think this is working correctly. If anyone finds that this is still an issue, please open a new issue.
