### ISSUE TITLE
Hub reporting as node?

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#67]
We noticed this is a first time running, we will ask some configuration settings

What is the default Role of this computer? (1 - node | 2 - hub | 3 - hub & node)

Default Value: 1
2  <-- I chose HUB
'2' was set as your value

What is the HOST for the Selenium Grid Hub?
Default Value: 127.0.0.1

'127.0.0.1' was set as your value

What is the PORT for the Selenium Grid Hub?
Default Value: 4444

'4444' was set as your value

Would you like WebDriver, IEDriver and ChromeDriver to auto update (1-yes/0-no)
Default Value: 1
1
'1' was set as your value
Current Selenium Driver Version: 2.44.0
Current IE Driver Version: 2.44.0
Current Chrome Driver Version: 2.12

Should this Node record test runs? (1-yes/0-no)
Default Value: 1 <-- Yes it asks this

**Comment by smccarthy** [comment]
@cktech529  I created a pull request for this fix.

**Comment by smccarthy** [comment]
This PR got merged in : https://github.com/groupon/Selenium-Grid-Extras/pull/82

@cktech529  or @dimacus  can you close?

Thanks.

**Comment by cktech529** [comment]
I could once I am back.

About that video bug, I moved domain for hub and nodes, changed hub to ip
vs host name and bam, it's recoding videos now. Very strange.

**Comment by smccarthy** [comment]
I just realized that this isn't in a downloadable release yet. Will have to wait until the next SGE release to test this fix (or build it yourself).

**Comment by cktech529** [comment]
Just saw that too,

I'll try and build myself. I'm on a windows system at the moment, is there
a process to point to?

Chris

**Comment by smccarthy** [comment]
You can probably just checkout the code and do mvn clean install -DskipTests (from the SeleniumGridExtras directory).

**Comment by smccarthy** [comment]
@cktech529 Closing this issue as it has been merged into master and new releases have it. Please reopen or open a new issue if you feel one requires it.
