### ISSUE TITLE
Using local IP and hostname (i.e. getHostIp and getHostName) when a node specifies a host

### ISSUE THREAD

**Issue by thomascramer** [groupon/Selenium-Grid-Extras#68]
We use docker containers for running our selenium nodes in our selenium grid. In our node config file we specify a "host" value so that it selenium hub knows how to connect to it.  However selenium-grid-extras is trying to use the local ip.  I think it just needs to pull the value from the "host" config option and if it isn't specified it should then look to local settings.  I'll try to put together a pull request this weekend...

**Comment by smccarthy** [comment]
@thomascramer , Closing this issue as you created a PR for it, and his been merged in, and a new release has been made since than.

**Comment by carlosmmelo** [comment]
Hey @thomascramer I would love to use this in docker containers. Would you please share your docker repo?
