### ISSUE TITLE
Mixed content security alert creates issue in IE 8

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#70]
When a https url is trying to access some content from a http domain, IE gives an security alert "Do you want to view only the webpage content that was delivered securely?"

In IE 9 & IE 10 we can prevent this alert by changing the mixed content security setting. But in IE 8 we cant prevent it from prompting this alert. And as of my understanding about Selenium Grid Extras, it is handling all the browser alert during execution in node. But in IE 8 when this alert is popping up, after some time it will disappear(for the alert handling behavior of Selenium Grid Extras) and all my test cases are failing.

After observing your ( @dimacus ) last few commits in Selenium Grid Extras, I think you are currently working on it. And I always thoroughly follow all your commits and changes.

So, if you have any idea or way to prevent it please share with me. It will be really helpful to me.

And also I like to mention that this project is simply a life savior for me. Great work.

**Comment by smccarthy** [comment]
Hi @rnavarette Sorry I took so long to get back to you. Currently, I don't think you can put a config option like this in the node config file. The way I handle it, is by having a Jenkins job (that just makes an HTTP request) to call any of the Selenium-Grid-Extras endpoints on all my nodes.

I hope this helps !

**Comment by rnavarette** [comment]
good enough for now I suppose :)

Thanks for the reply

**Comment by smccarthy** [comment]
You're welcome! @dimacus I think this can be closed.
