### ISSUE TITLE
Unresponsive GridExtras Servlet

### ISSUE THREAD

**Issue by rnavarette** [groupon/Selenium-Grid-Extras#77]
Hello,

I'm finding that the Grid Extras servlet running on port 3000 responds fine only until I run a test on the given node.  Once a test is run on that node, all attempts to connect to the web page time out.  The grid is still registered with the hub and can run tests, but the Grid Extras capabilities are not available.  Is this something that anyone has seen before?

Also, I tried setting the restart after N tests setting to 1 to work around this, but it seems to be ignored (I believe there is a separate issue logged for this).  I do not see any errors in the log in my case though, it just simply does not restart.

Thanks,
ray

**Comment by smccarthy** [comment]
@rnavarette What version of Selenium-Grid-Extras are you using ?

**Comment by rnavarette** [comment]
1.7.1-SNAPSHOT (from 2015-11-21 i believe)

**Comment by smccarthy** [comment]
Can you try to delete the proxy from the node configuration file and restart the node(s)? I just want to see if that will "fix" the issue, for now. I believe I had a similar issue and that is how I got around it.

**Comment by rnavarette** [comment]
The config on the hub I assume?

**Comment by smccarthy** [comment]
Do you store the configs on the hub? If so, than yes, update the node config on the hub, than restart your selenium grid extras jar on the node, and it will auto get it from the hub (if you set it up like that).

**Comment by rnavarette** [comment]
Seems to have done the trick.  Am i losing anything without the proxy setting?

**Comment by smccarthy** [comment]
@dimacus  Do you know ? I think it has to do with restarting the node after X tests, and I also see some stuff about video recording in there. This might be related to #66  ?

**Comment by rgonalo** [comment]
I think that this issue was solved in https://github.com/groupon/Selenium-Grid-Extras/issues/74 
After the first test, the grid extras servlet was blocked due to a stream deadlock

**Comment by smccarthy** [comment]
Thanks @rgonalo  . @rnavarette Please check and see if this still occurs for you. There have been a few releases since this issue was last updated.

**Comment by smccarthy** [comment]
Closing this as no response, and it could have been fixed by #74 . Please post back if this is still an issue.
