### ISSUE TITLE
Less Option in Selection of Node Platform (WIN8 & WIN8_1 are not there)

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#78]
For now the existing options for node platform are : WINDOWS|XP|VISTA|MAC|LINUX|UNIX|ANDROID.

So, to run the test cases in Windows 8 machine, the platform need to be set as default WINDOWS.
But, Selenium has introduced two enum WIN8 and WIN8_1 for WINDOWS 8 and WINDOWS 8.1 respectively for setting up the OS platform.
Source : https://code.google.com/p/selenium/wiki/GridPlatforms

So, if someone, in his code, set platform as WIN8 to run his test on windows 8 machine and configure the node of Windows 8 machine with WINDOWS option, his test must fail as it leads to the failiure of driver creation.
So, these two options are need to be included in case of platform selection.

**Comment by smccarthy** [comment]
@sohammukherjee  Which version are you using? I am using the latest (1.7.1) and I see :
      System.out.println("What is node Platform? (WINDOWS|XP|VISTA|WIN8|WIN8_1|MAC|LINUX|UNIX|ANDROID)");

It attempts to guess the correct version, but you can still enter the correct value (WIN8 or WIN8_1) if you want. From your issue, it looks like you have an older version since you don't have WIN8 and WIN8_1 in your output.

**Comment by smccarthy** [comment]
It looks like it was added on Oct 3rd 2014 commit : https://github.com/groupon/Selenium-Grid-Extras/commit/d2a59b537a664680fa98df109a7f871df97e9d85 

From the releases, 1.5.2 and newer should have this.

Hope this helps!

**Comment by sohammukherjee** [comment]
Thanks for your ans.
I think my selenium grid extras version is need to be updated.
Thanks.
