### ISSUE TITLE
SafariDriver stops working on reaching a certain page in Mac OS X version 10.9.3 and Safari 7.0.3

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#79]
Our selenium grid is setup on GridExtras. All our testcases run properly on the MAC setup on Gridextras. But there is a certain client URL which loads through the safari driver and after that nothing happens, the driver basically stops and finally the MAC node releases the browser due to in browser time out. The application under test is developed on DOJO framework.

**Comment by smccarthy** [comment]
@sohammukherjee  Which version of Selenium Grid Extras? I know there is a bug with Selenium 2.46.0 (released on June 4th) that had a fix commited June 9th. So hopefully the next version of selenium works with Safari. I will test this out after a new selenium release.

**Comment by sohammukherjee** [comment]
Yes it works for me. Thanks.
