### ISSUE TITLE
newSessionWaitTimeout capability is not working

### ISSUE THREAD

**Issue by sohammukherjee** [groupon/Selenium-Grid-Extras#83]
According to Selenium Grid 2 configuration, if 'newSessionWaitTimeout' capability is not set in the HubConfig file, then the value of this capability is set to its default value '-1' which means no timeout for the waiting request. And also all the nodes use this value from the hub if this is set.

Now, I have faced three issues here:

1. If i dont set any value of this capability in the hubconfig file, then by default it is set as 120000 ms for all the nodes.

2. If i set any value of this capability in the hubconfig file, then also it is set as 120000 ms for all the nodes.

3. If i set any value of this capability in the nodeconfig file, then it shows the changed value in the Grid Console but not in effect. Then also after 120000 ms(2 min) all the waiting test requests are timed out.

**Comment by smccarthy** [comment]
1 and 2 are not "issues" I think. That's how Selenium Grid works (if I understand your comments).

**Comment by sohammukherjee** [comment]
That's how Selenium Grid works or Selenium Grid extras works to be precise.
Because I may be wrong, but as far as I know, if newSessionWaitTimeout capability is not set, then it picks it's default value which is -1 that means no timeout.

Ok, now for the third issue what we can do? Because I face this scenario for IE every now and then. As only one instance of Internet Explorer can open on a particular machine, 5 different user sharing same Selenium Hub send 5 requests of IE 9 then 1 test will run and 4 other will be waiting and after 2 mins those 4 requests are timed out.

**Comment by smccarthy** [comment]
Ok you're right for number 1. So do you agree that number 2 is not an issue?

**Comment by sohammukherjee** [comment]
Ok, my 2nd point is not an issue as such I agree.

But I'm more concern about my 1st and 3rd point. So, is there any way around to fix these issues?? Because I have really stuck here.

**Comment by smccarthy** [comment]
@sohammukherjee I created a new hub/node (option 3) machine, and it defaults newSessionWaitTimeout to 25000 in the hub_4444.json. If I remove that from the hub_4444.json file, it gets set to -1 from the grid console.

Are you talking about the "browserTimeout" or "timeout" options instead ? These two get defaulted to 120000 in Selenium-Grid-Extras.

**Comment by sohammukherjee** [comment]
Ok, so let me explain you my entire scenario.

I have created a hub machine(option 2) and five different node machine(option 1).

Regarding my first issue, I haven't put anything about newSessionWaitTimeout  capability either in hubconfig file or in node config file. Though in bode configuration file it is shown that the newSessionWaitTimeout  is 120000. Screenshot is attached below:
![capture1](https://cloud.githubusercontent.com/assets/8623750/5772046/bdc92bf4-9d70-11e4-87b8-9cd11ab74886.PNG)

now regarding my third issue, I have put newSessionWaitTimeout  capability in nodeconfig file of a individual node machine as '-1'. After that in node configuratin page it is clearly shown that this capability is set as '-1'. But is value is not in effect. Because if this capability is set to be '-1' then there should be no timeout for waiting requests. But, even if the the capability is '-1' then also all the waiting requests are time out after certain time(to be precise 2 mins). Screenshot is attached below:
![capture 2](https://cloud.githubusercontent.com/assets/8623750/5772080/5c9f0172-9d71-11e4-832b-ce5980d3a3e1.PNG)

Here I'm also attaching the screenshots of my hubconfig file and one of the node config file for your reference:

![capture6](https://cloud.githubusercontent.com/assets/8623750/5772157/cec01132-9d72-11e4-8c26-81d84b657d35.PNG)
![capture7](https://cloud.githubusercontent.com/assets/8623750/5772158/cec795c4-9d72-11e4-9520-d1164bf4e1e2.PNG)
![capture8](https://cloud.githubusercontent.com/assets/8623750/5772156/cebb1362-9d72-11e4-96d6-146d2ac04717.PNG)

**Comment by smccarthy** [comment]
Try to remove 
"capabilities": [],
from your hub config json file. I don't think it should be there.

Also, newSessionWaitTimeout is only set in the hub config file, not the node config file. Remove it from the node config file.

Than try and start your grid. I hope that it gets set to -1 by default. Than try and set it to whatever you like, in the hub config file (not node config file).

Also, which version of Selenium-Grid-Extras are you using? I am on 1.7.1 (plus a few commits for browser version detection).

Let me know the outcome. Thanks.

**Comment by sohammukherjee** [comment]
I was using version 1.6.1 (a little bit older).

Now i update it to 1.7.1. The major change i noticed that there is an extra json file is included for hub configuration namely hub_4444.json. And we have to put all these configurable capabilities.

Thank you for all your kind support. Now my problem is solved. I set the value of this capability as -1 in the hubconfig file and it is reflected in all of my nodes.

Thank you again. This problem is such a bottleneck for me since last week. And finally it is solved. Thank You.

**Comment by sohammukherjee** [comment]
So, I think now we can close this issue.

**Comment by smccarthy** [comment]
Thank you! Glad it is working.
