### ISSUE TITLE
How do we pass custom classes to the hub

### ISSUE THREAD

**Issue by chdavi** [groupon/Selenium-Grid-Extras#94]
Is there a way to pass custom classes to the hub? I need to run a custom Prioritizer and Capability Matcher and didn't see a way of getting the custom classes to the hub start command's classpath argument.

I can have a pull request ready in short order if this is something that isn't supported yet.

**Comment by smccarthy** [comment]
@chdavi I was working on a feature for adding a custom capability matcher, but that was a few months ago and I didn't finish it. It would definitely be a good feature if you are still interested in creating a PR for it.

Thank you.

**Comment by StephenCavender** [comment]
This would be a great feature! I'd like to take advantage of a Sauce plug-in but can't load it into my seleniun grid extras instance!
http://sauceio.com/index.php/2012/09/introducing-the-sauce-plugin-for-selenium-grid/

**Comment by chdavi** [comment]
I will see if I can finish it up this week.
