### ISSUE TITLE
Is there any way to see Console of Hub 172.0.0.1:4444/grid/console#

### ISSUE THREAD

**Issue by divyanshugarg** [groupon/Selenium-Grid-Extras#95]
Is there any way to see Console of Hub 172.0.0.1:4444/grid/console#?

Want to know below things from a single place (e.g. Console):
1- What are the nodes are register currently
2- Current status of each node? What are the nodes are free and busy
3- What are the different browsers/simulator/devices registrty in each ndoe (IE, Firefox, Chrome, iPhone)
4- What are the max sessions in each Nodes
5-  etc

**Comment by smccarthy** [comment]
I am confused by this. Doesn't the regular Selenium Grid Hub show this information ?

**Comment by divyanshugarg** [comment]
I didn't find the option to see HUB console when using 'Selenium-Grid-Extras' jar. Like, when we use "java -jar selenium-server-standalone-2.40.0.jar -port 4444 -role hub"  then we can see HUB console via localhost:4444/grid/console/#

**Comment by smccarthy** [comment]
When you start the SeleniumGridExtras jar, it will start the hub and/or the node. When you first start the SeleniumGridExtras jar, it will ask you what that machine will be used for (hub, node, or hub + node). If you select hub and node, or just hub, you will be able to go to that machine's ip:4444/grid/console .

**Comment by smccarthy** [comment]
@divyanshugarg Is this still an issue?

**Comment by divyanshugarg** [comment]
No. Please close it.

**Comment by smccarthy** [comment]
Thanks for checking so quickly! Closing.
