### ISSUE TITLE
Restart Nodes only after no other tests are running on that node

### ISSUE THREAD

**Issue by sinisterrook** [groupon/Selenium-Grid-Extras#99]
Hi I'm having an issue where the node restarts after 10 runs (which it should) however it does it mid test cycle.  Any way to force it to check, possibly longer, for incoming data before killing my tests?

**Comment by VinceBZH** [comment]
Hi,

I'm also interesting in by this feature.
Before restarting the node, it would be good to wait 1 minute : if some tests are triggered it postpones the restart, if no test, it schedules the restart.

**Comment by smccarthy** [comment]
I am very interested in this feature as well. However, it would be a decent sized change I think.

**Comment by smccarthy** [comment]
@VinceBZH @sinisterrook I have updated the title and tagged this as enhancement.

**Comment by dimacus** [comment]
Adding smarter checks to see if the node is currently busy. If there is another test running on the node, wait for the test to finish but don't allow any new sessions to start

https://github.com/groupon/Selenium-Grid-Extras/commit/55c62f660f1a0d4858f4e39afae274b98b3a7d29
